[package]
name = "finkit-factor"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Factor implementations for the Finkit quantitative engine"
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
finkit-array = { path = "../finkit-array" }
finkit-math = { path = "../finkit-math" }
finkit-series = { path = "../finkit-series" }
