[package]
name = "finkit-java"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Java bindings for finkit"

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
finkit = { path = "../../core" }
finkit-visualization = { path = "../../visualization", features = ["svg"] }
jni = { workspace = true }
lazy_static = "1.4"
ndarray = { workspace = true }
serde_json = { workspace = true }
finkit-ffi-common = { path = "../ffi-common" }