//! 黄金 CSV 加载与容差断言
//!
//! 该模块为黄金测试（golden / regression test）提供基础设施。
//!
//! 典型工作流：
//! 1. 由 [`scripts/generate_golden.py`](../../../../../scripts/generate_golden.py) 调用
//!    TA-Lib / 同花顺导出参考 CSV，存到 `tests/golden/<name>.csv`
//! 2. 在测试中调用 [`load_golden`] 加载参考值
//! 3. 调用本库对应指标得到实际值
//! 4. 用 [`assert_approx_eq_slice`] 在 1e-9 / 1e-6 容差下逐值对比
//!
//! CSV 格式约定：
//! - 一行一个标量
//! - 注释行以 `#` 开头（如 `# Generated by TA-Lib 0.6.x`）
//! - 空行被忽略
//! - 多列格式支持 `value,extra_col1,extra_col2`（仅第一列被解析）

use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::Path;

/// 标准数值容差（与 TA-Lib / 同花顺绝对值输出对齐）
pub const DEFAULT_TOLERANCE: f64 = 1e-9;

/// 百分比模式容差（hv / natr 等以百分号为单位的指标）
pub const PERCENT_TOLERANCE: f64 = 1e-6;

/// 从黄金 CSV 文件加载第一列数值。
///
/// 行为约定：
/// - 跳过以 `#` 开头的注释行
/// - 跳过空行
/// - 每行取 `,` 之前的第一段，trim 后 parse 为 `f64`
/// - 任何无法解析的行静默忽略（保证 forward-compat 多列 CSV）
///
/// # Panics
/// - 文件打不开时 panic
pub fn load_golden<P: AsRef<Path>>(path: P) -> Vec<f64> {
    let file = File::open(path.as_ref()).expect("open golden");
    let reader = BufReader::new(file);
    reader
        .lines()
        .filter_map(|l| l.ok())
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .filter_map(|l| l.split(',').next().and_then(|s| s.trim().parse().ok()))
        .collect()
}

/// 跳过注释头，返回 CSV 中所有非空、非注释行的原始字符串。
///
/// 配合多列 CSV 解析使用（例如 BBANDS 输出 upper / middle / lower 三列）。
#[allow(dead_code)] // re-exported for future Phase 3 / Phase 8 golden tests
pub fn load_golden_lines<P: AsRef<Path>>(path: P) -> Vec<String> {
    let file = File::open(path.as_ref()).expect("open golden");
    let reader = BufReader::new(file);
    reader
        .lines()
        .filter_map(|l| l.ok())
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .collect()
}

/// 逐值容差断言。
///
/// # Panics
/// - 长度不匹配：明确指出期望与实际长度
/// - 任意下标处差值超过 `tol`：明确指出下标与差值
pub fn assert_approx_eq_slice(expected: &[f64], actual: &[f64], tol: f64) {
    assert_eq!(
        expected.len(),
        actual.len(),
        "length mismatch: expected {}, got {}",
        expected.len(),
        actual.len()
    );
    for (i, (&e, &a)) in expected.iter().zip(actual.iter()).enumerate() {
        let diff = (e - a).abs();
        if diff > tol {
            panic!(
                "idx {}: expected {}, got {}, diff {} (tol {})",
                i, e, a, diff, tol
            );
        }
    }
}

/// 黄金测试 fixture 根目录（`tests/golden/`）。
///
/// 通过 `CARGO_MANIFEST_DIR` 解析到 workspace 的 `tests/golden/`，与现有
/// `core/tests/golden_tests.rs` 的 `golden_dir()` 行为一致。
#[allow(dead_code)] // re-exported for future Phase 3 / Phase 8 golden tests
pub fn golden_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../tests/golden")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn write_tmp(content: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir();
        let path = dir.join(format!(
            "alpha_ta_golden_test_{}_{}.csv",
            std::process::id(),
            rand_u64()
        ));
        let mut f = File::create(&path).expect("create tmp");
        f.write_all(content.as_bytes()).expect("write tmp");
        path
    }

    fn rand_u64() -> u64 {
        use std::time::{SystemTime, UNIX_EPOCH};
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos() as u64)
            .unwrap_or(0)
    }

    #[test]
    fn load_golden_skips_comments_and_blanks() {
        let path = write_tmp(
            "# Generated by TA-Lib 0.6.x\n\
             1.0\n\
             \n\
             2.0\n\
             # trailing comment\n\
             3.0,extra,col\n",
        );
        let vals = load_golden(&path);
        assert_eq!(vals, vec![1.0, 2.0, 3.0]);
        let _ = std::fs::remove_file(path);
    }

    #[test]
    fn assert_approx_eq_slice_passes_within_tol() {
        assert_approx_eq_slice(&[1.0, 2.0, 3.0], &[1.0 + 1e-12, 2.0, 3.0], 1e-9);
    }

    #[test]
    #[should_panic(expected = "length mismatch")]
    fn assert_approx_eq_slice_panics_on_length() {
        assert_approx_eq_slice(&[1.0, 2.0], &[1.0], 1e-9);
    }

    #[test]
    #[should_panic(expected = "idx 1")]
    fn assert_approx_eq_slice_panics_on_diff() {
        assert_approx_eq_slice(&[1.0, 2.0, 3.0], &[1.0, 2.5, 3.0], 1e-9);
    }
}
