//! Candlestick pattern formula shims, generated by `define_cdl_formula_function!`.

use super::prelude::*;

pub(crate) fn candlestick_values<F>(
    ctx: &FormulaContext,
    args: &[Array1<f64>],
    name: &str,
    detector: F,
) -> Result<Array1<f64>, FormulaError>
where
    F: Fn(&[f64], &[f64], &[f64], &[f64]) -> crate::error::Result<Array1<i32>>,
{
    ensure_args_len(name, args, 4)?;
    let open = args[0].as_slice().unwrap();
    let high = args[1].as_slice().unwrap();
    let low = args[2].as_slice().unwrap();
    let close = args[3].as_slice().unwrap();
    match detector(open, high, low, close) {
        Ok(values) => Ok(values.mapv(|value| value as f64)),
        Err(_) => Ok(nan_vec(ctx.data_len)),
    }
}

macro_rules! define_cdl_formula_function {
    ($wrapper:ident, $name:literal, $detector:path) => {
        pub(crate) fn $wrapper(
            ctx: &FormulaContext,
            args: &[Array1<f64>],
        ) -> Result<Array1<f64>, FormulaError> {
            candlestick_values(ctx, args, $name, $detector)
        }
    };
}

define_cdl_formula_function!(fn_cdl_2crows, "CDL2CROWS", lib_candlestick::cdl_2crows);
define_cdl_formula_function!(
    fn_cdl_3blackcrows,
    "CDL3BLACKCROWS",
    lib_candlestick::cdl_3black_crows
);
define_cdl_formula_function!(fn_cdl_3inside, "CDL3INSIDE", lib_candlestick::cdl_3inside);
define_cdl_formula_function!(
    fn_cdl_3linestrike,
    "CDL3LINESTRIKE",
    lib_candlestick::cdl_3linestrike
);
define_cdl_formula_function!(
    fn_cdl_3outside,
    "CDL3OUTSIDE",
    lib_candlestick::cdl_3outside
);
define_cdl_formula_function!(
    fn_cdl_3starsinsouth,
    "CDL3STARSINSOUTH",
    lib_candlestick::cdl_3starsinsouth
);
define_cdl_formula_function!(
    fn_cdl_3whitesoldiers,
    "CDL3WHITESOLDIERS",
    lib_candlestick::cdl_3white_soldiers
);
define_cdl_formula_function!(
    fn_cdl_abandonedbaby,
    "CDLABANDONEDBABY",
    lib_candlestick::cdl_abandoned_baby
);
define_cdl_formula_function!(
    fn_cdl_advanceblock,
    "CDLADVANCEBLOCK",
    lib_candlestick::cdl_advanceblock
);
define_cdl_formula_function!(
    fn_cdl_belthold,
    "CDLBELTHOLD",
    lib_candlestick::cdl_belthold
);
define_cdl_formula_function!(
    fn_cdl_breakaway,
    "CDLBREAKAWAY",
    lib_candlestick::cdl_breakaway
);
define_cdl_formula_function!(
    fn_cdl_closingmarubozu,
    "CDLCLOSINGMARUBOZU",
    lib_candlestick::cdl_closingmarubozu
);
define_cdl_formula_function!(
    fn_cdl_concealbabyswall,
    "CDLCONCEALBABYSWALL",
    lib_candlestick::cdl_concealbabyswall
);
define_cdl_formula_function!(
    fn_cdl_counterattack,
    "CDLCOUNTERATTACK",
    lib_candlestick::cdl_counterattack
);
define_cdl_formula_function!(
    fn_cdl_darkcloudcover,
    "CDLDARKCLOUDCOVER",
    lib_candlestick::cdl_darkcloudcover
);
define_cdl_formula_function!(
    fn_cdl_dojistar,
    "CDLDOJISTAR",
    lib_candlestick::cdl_doji_star
);
define_cdl_formula_function!(
    fn_cdl_eveningdojistar,
    "CDLEVENINGDOJISTAR",
    lib_candlestick::cdl_eveningdojistar
);
define_cdl_formula_function!(
    fn_cdl_eveningstar,
    "CDLEVENINGSTAR",
    lib_candlestick::cdl_eveningstar
);
define_cdl_formula_function!(
    fn_cdl_gapsidesidewhite,
    "CDLGAPSIDESIDEWHITE",
    lib_candlestick::cdl_gap_side_white
);
define_cdl_formula_function!(
    fn_cdl_haramicross,
    "CDLHARAMICROSS",
    lib_candlestick::cdl_haramicross
);
define_cdl_formula_function!(
    fn_cdl_highwave,
    "CDLHIGHWAVE",
    lib_candlestick::cdl_highwave
);
define_cdl_formula_function!(fn_cdl_hikkake, "CDLHIKKAKE", lib_candlestick::cdl_hikkake);
define_cdl_formula_function!(
    fn_cdl_hikkakemod,
    "CDLHIKKAKEMOD",
    lib_candlestick::cdl_hikkake_mod
);
define_cdl_formula_function!(
    fn_cdl_homingpigeon,
    "CDLHOMINGPIGEON",
    lib_candlestick::cdl_homing_pigeon
);
define_cdl_formula_function!(
    fn_cdl_identical3crows,
    "CDLIDENTICAL3CROWS",
    lib_candlestick::cdl_identical3crows
);
define_cdl_formula_function!(fn_cdl_inneck, "CDLINNECK", lib_candlestick::cdl_inneck);
define_cdl_formula_function!(
    fn_cdl_invertedhammer,
    "CDLINVERTEDHAMMER",
    lib_candlestick::cdl_invertedhammer
);
define_cdl_formula_function!(fn_cdl_kicking, "CDLKICKING", lib_candlestick::cdl_kicking);
define_cdl_formula_function!(
    fn_cdl_kickingbylength,
    "CDLKICKINGBYLENGTH",
    lib_candlestick::cdl_kickingbylength
);
define_cdl_formula_function!(
    fn_cdl_ladderbottom,
    "CDLLADDERBOTTOM",
    lib_candlestick::cdl_ladder_bottom
);
define_cdl_formula_function!(
    fn_cdl_longleggeddoji,
    "CDLLONGLEGGEDDOJI",
    lib_candlestick::cdl_longleggeddoji
);
define_cdl_formula_function!(
    fn_cdl_longline,
    "CDLLONGLINE",
    lib_candlestick::cdl_longline
);
define_cdl_formula_function!(
    fn_cdl_matchinglow,
    "CDLMATCHINGLOW",
    lib_candlestick::cdl_matchinglow
);
define_cdl_formula_function!(fn_cdl_mathold, "CDLMATHOLD", lib_candlestick::cdl_mathold);
define_cdl_formula_function!(
    fn_cdl_morningdojistar,
    "CDLMORNINGDOJISTAR",
    lib_candlestick::cdl_morningdojistar
);
define_cdl_formula_function!(
    fn_cdl_morningstar,
    "CDLMORNINGSTAR",
    lib_candlestick::cdl_morningstar
);
define_cdl_formula_function!(fn_cdl_onneck, "CDLONNECK", lib_candlestick::cdl_onneck);
define_cdl_formula_function!(
    fn_cdl_rickshawman,
    "CDLRICKSHAWMAN",
    lib_candlestick::cdl_rickshawman
);
define_cdl_formula_function!(
    fn_cdl_risefall3methods,
    "CDLRISEFALL3METHODS",
    lib_candlestick::cdl_rise_fall_3methods
);
define_cdl_formula_function!(
    fn_cdl_separatinglines,
    "CDLSEPARATINGLINES",
    lib_candlestick::cdl_separatinglines
);
define_cdl_formula_function!(
    fn_cdl_shortline,
    "CDLSHORTLINE",
    lib_candlestick::cdl_shortline
);
define_cdl_formula_function!(
    fn_cdl_stalledpattern,
    "CDLSTALLEDPATTERN",
    lib_candlestick::cdl_stalledpattern
);
define_cdl_formula_function!(
    fn_cdl_sticksandwich,
    "CDLSTICKSANDWICH",
    lib_candlestick::cdl_sticksandwich
);
define_cdl_formula_function!(fn_cdl_takuri, "CDLTAKURI", lib_candlestick::cdl_takuri);
define_cdl_formula_function!(
    fn_cdl_tasukigap,
    "CDLTASUKIGAP",
    lib_candlestick::cdl_tasukigap
);
define_cdl_formula_function!(
    fn_cdl_thrusting,
    "CDLTHRUSTING",
    lib_candlestick::cdl_thrusting
);
define_cdl_formula_function!(fn_cdl_tristar, "CDLTRISTAR", lib_candlestick::cdl_tristar);
define_cdl_formula_function!(
    fn_cdl_unique3river,
    "CDLUNIQUE3RIVER",
    lib_candlestick::cdl_unique3river
);
define_cdl_formula_function!(
    fn_cdl_upsidegap2crows,
    "CDLUPSIDEGAP2CROWS",
    lib_candlestick::cdl_upsidegap2crows
);
define_cdl_formula_function!(
    fn_cdl_xsidegap3methods,
    "CDLXSIDEGAP3METHODS",
    lib_candlestick::cdl_xsidegap3methods
);

pub(crate) fn fn_cdl_doji(
    ctx: &FormulaContext,
    args: &[Array1<f64>],
) -> Result<Array1<f64>, FormulaError> {
    candlestick_values(ctx, args, "CDLDOJI", lib_candlestick::cdl_doji)
}

pub(crate) fn fn_cdl_dragonflydoji(
    ctx: &FormulaContext,
    args: &[Array1<f64>],
) -> Result<Array1<f64>, FormulaError> {
    candlestick_values(
        ctx,
        args,
        "CDLDRAGONFLYDOJI",
        lib_candlestick::cdl_dragonflydoji,
    )
}

pub(crate) fn fn_cdl_gravestonedoji(
    ctx: &FormulaContext,
    args: &[Array1<f64>],
) -> Result<Array1<f64>, FormulaError> {
    candlestick_values(
        ctx,
        args,
        "CDLGRAVESTONEDOJI",
        lib_candlestick::cdl_gravestonedoji,
    )
}

pub(crate) fn fn_cdl_engulfing(
    ctx: &FormulaContext,
    args: &[Array1<f64>],
) -> Result<Array1<f64>, FormulaError> {
    candlestick_values(ctx, args, "CDLENGULFING", lib_candlestick::cdl_engulfing)
}

pub(crate) fn fn_cdl_hammer(
    ctx: &FormulaContext,
    args: &[Array1<f64>],
) -> Result<Array1<f64>, FormulaError> {
    candlestick_values(ctx, args, "CDLHAMMER", lib_candlestick::cdl_hammer)
}

pub(crate) fn fn_cdl_hangingman(
    ctx: &FormulaContext,
    args: &[Array1<f64>],
) -> Result<Array1<f64>, FormulaError> {
    candlestick_values(ctx, args, "CDLHANGINGMAN", lib_candlestick::cdl_hangingman)
}

pub(crate) fn fn_cdl_harami(
    ctx: &FormulaContext,
    args: &[Array1<f64>],
) -> Result<Array1<f64>, FormulaError> {
    candlestick_values(ctx, args, "CDLHARAMI", lib_candlestick::cdl_harami)
}

pub(crate) fn fn_cdl_marubozu(
    ctx: &FormulaContext,
    args: &[Array1<f64>],
) -> Result<Array1<f64>, FormulaError> {
    candlestick_values(ctx, args, "CDLMARUBOZU", lib_candlestick::cdl_marubozu)
}

pub(crate) fn fn_cdl_piercing(
    ctx: &FormulaContext,
    args: &[Array1<f64>],
) -> Result<Array1<f64>, FormulaError> {
    candlestick_values(ctx, args, "CDLPIERCING", lib_candlestick::cdl_piercing)
}

pub(crate) fn fn_cdl_shootingstar(
    ctx: &FormulaContext,
    args: &[Array1<f64>],
) -> Result<Array1<f64>, FormulaError> {
    candlestick_values(
        ctx,
        args,
        "CDLSHOOTINGSTAR",
        lib_candlestick::cdl_shootingstar,
    )
}

pub(crate) fn fn_cdl_spinningtop(
    ctx: &FormulaContext,
    args: &[Array1<f64>],
) -> Result<Array1<f64>, FormulaError> {
    candlestick_values(
        ctx,
        args,
        "CDLSPINNINGTOP",
        lib_candlestick::cdl_spinningtop,
    )
}
