[package]
name = "finkit-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "C FFI bindings for Finkit"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
finkit = { path = "../../core" }
libc = "0.2"
serde_json = { workspace = true }
ndarray = { workspace = true }