[package]
name = "finkit-series"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Time series primitives for the Finkit quantitative engine"
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
finkit-array = { path = "../finkit-array" }
