[package]
name = "finkit-visualization"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
png = { version = "0.17", optional = true }
fontdue = "0.9"
finkit = { path = "../core" }

[features]
default = ["svg"]
svg = []
png = ["dep:png"]
html = ["svg"]