<#
.SYNOPSIS
  AlphaTA — one-click AlphaTA vs TA-Lib C head-to-head comparison on Windows.

.DESCRIPTION
  PowerShell 7+ equivalent of scripts/bench-vs-talib.sh.
  Reads from target/criterion/ after `cargo bench --bench talib_c_comparison
  --features talib-c`, then invokes scripts/bench_report.py and renders a
  compact summary table to dist/bench/summary.md.

.PARAMETER Precision
  Run the precision-parity step (requires AlphaTA + talib Python packages).

.PARAMETER JsonOut
  Path for the per-indicator JSON. Defaults to dist/bench/results.json.

.PARAMETER MarkdownOut
  Path for the head-to-head markdown. Defaults to dist/bench/alpha-ta-vs-talib.md.
#>
[CmdletBinding()]
param(
    [switch] $Precision,
    [string] $JsonOut,
    [string] $MarkdownOut
)

$ErrorActionPreference = "Stop"

$ScriptDir   = (Resolve-Path "$PSScriptRoot").Path
$Root        = (Resolve-Path "$ScriptDir\..").Path
$Out         = Join-Path $Root "dist\bench"
$null        = New-Item -ItemType Directory -Force -Path $Out
$JsonOut     = if ($JsonOut)     { $JsonOut }     else { Join-Path $Out "results.json" }
$MarkdownOut = if ($MarkdownOut) { $MarkdownOut } else { Join-Path $Out "alpha-ta-vs-talib.md" }

function Write-Hdr  ([string]$m) { Write-Host ""; Write-Host "=== $m ===" -ForegroundColor DarkCyan }
function Write-Ok   ([string]$m) { Write-Host "  [OK]   $m" -ForegroundColor Green }
function Write-Warn ([string]$m) { Write-Host "  [WARN] $m" -ForegroundColor Yellow }
function Write-Err  ([string]$m) { Write-Host "  [FAIL] $m" -ForegroundColor Red }

Write-Hdr "[bench-vs-talib] step 1/3: TA-Lib C detection"
$taLibRoot = $env:TA_LIBRARY_PATH
if (-not $taLibRoot) {
    if (Test-Path "C:\ta-lib") {
        $env:TA_LIBRARY_PATH = "C:\ta-lib\lib"
        $env:TA_INCLUDE_PATH = "C:\ta-lib\include"
        Write-Ok "using C:\ta-lib"
    } else {
        Write-Warn "TA-Lib not detected."
        Write-Warn "Download ta-lib-0.6.4-windows-x86_64.zip from"
        Write-Warn "  https://github.com/ta-lib/ta-lib/releases"
        Write-Warn "and extract to C:\ta-lib."
        Write-Warn "Then set TA_LIBRARY_PATH and TA_INCLUDE_PATH and re-run."
        # Continue anyway — cargo will emit a clear error and the user can
        # see what to do.
    }
} else {
    Write-Ok "TA_LIBRARY_PATH=$taLibRoot"
}

Write-Hdr "[bench-vs-talib] step 2/3: cargo bench"
Push-Location (Join-Path $Root "core")
try {
    cargo bench --bench talib_c_comparison --features talib-c
    if ($LASTEXITCODE -ne 0) {
        Write-Err "cargo bench failed with exit code $LASTEXITCODE"
        exit $LASTEXITCODE
    }
} finally { Pop-Location }

Write-Hdr "[bench-vs-talib] step 3/3: render markdown + JSON"
& python $ScriptDir\bench_report.py `
    --criterion-dir (Join-Path $Root "target\criterion") `
    --output        $MarkdownOut `
    --json-out      $JsonOut

# Render compact summary
$summaryPath = Join-Path $Out "summary.md"
$env:JSON_OUT = $JsonOut
$env:SUMMARY_OUT = $summaryPath

# Inline summary renderer (PowerShell has no bash heredocs, so we use a
# here-string + temp .py file).
$summaryPy = @'
import datetime, json, os, pathlib
res = json.loads(pathlib.Path(os.environ["JSON_OUT"]).read_text())
bench = res.get("benchmarks", {})
out = os.environ.get("SUMMARY_OUT", "summary.md")
generated = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

lines = [
    "# AlphaTA vs TA-Lib C — Head-to-Head Summary",
    "",
    f"> Auto-generated by `scripts/bench-vs-talib.ps1` on {generated}",
    "",
    "| Indicator | Category | AlphaTA (us) | TA-Lib C (us) | Speedup | Δ (pp) | Status |",
    "|---|---|---|---|---|---|---|",
]
for k in sorted(bench.keys()):
    v = bench[k]
    delta = v.get("delta_pp")
    delta_s = "—" if delta is None else f"{delta:.2e}"
    lines.append(
        f"| {k} | {v.get('category','?')} | {v['fta_us']:.2f} | {v['talib_us']:.2f} | "
        f"{v['speedup']:.2f}x | {delta_s} | {v['status']} |"
    )

total = len(bench)
faster = sum(1 for v in bench.values() if v['status'] == "✅")
slower = sum(1 for v in bench.values() if v['status'] == "❌")
warn_n = sum(1 for v in bench.values() if v['status'] == "⚠️")
lines += [
    "",
    f"- **Total**: {total}",
    f"- **AlphaTA faster**: {faster}",
    f"- **AlphaTA within 25%**: {warn_n}",
    f"- **AlphaTA >25% slower**: {slower}",
]
pathlib.Path(out).write_text("\n".join(lines))
'@

$tmpPy = [System.IO.Path]::GetTempFileName() + ".py"
[System.IO.File]::WriteAllText($tmpPy, $summaryPy, [System.Text.Encoding]::UTF8)
try {
    & python $tmpPy
} finally {
    Remove-Item $tmpPy -ErrorAction SilentlyContinue
}
Write-Ok "summary: $summaryPath"

if ($Precision) {
    Write-Hdr "[bench-vs-talib] step 4/4: precision parity"
    try {
        & python $ScriptDir\bench_vs_talib_precision.py `
            --json-out (Join-Path $Out "precision.json") `
            --results  $JsonOut `
            --output   (Join-Path $Out "precision.md")
        Write-Ok "precision merged into $JsonOut"
    } catch {
        Write-Warn "precision step failed: $_"
    }
}

Write-Hdr "[bench-vs-talib] DONE"
Get-ChildItem $Out | Format-Table Name, Length -AutoSize
