#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# AlphaTA — one-click AlphaTA vs TA-Lib C head-to-head comparison.
#
# Steps:
#   1. Detect (and install if missing) TA-Lib C library + headers.
#   2. Run `cargo bench --bench talib_c_comparison --features talib-c` to
#      collect Criterion JSON estimates.
#   3. Run scripts/bench_report.py to render docs/BENCHMARK_REPORT.md and a
#      machine-readable dist/bench/results.json (with per-indicator speedup).
#   4. Render a compact head-to-head summary table to dist/bench/summary.md
#      from the JSON.
#   5. (Optional) Run scripts/bench_vs_talib_precision.py to populate
#      delta_pp in the same results.json — only when --precision is passed.
#
# Outputs (under dist/bench/):
#   * alpha-ta-vs-talib.md  — full markdown (copy of docs/BENCHMARK_REPORT.md)
#   * results.json       — machine-readable per-indicator data
#   * summary.md         — compact one-glance table
#   * precision.md       — (only with --precision) precision parity table
#   * precision.json     — (only with --precision) raw precision numbers
# ----------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT="$( cd "${SCRIPT_DIR}/.." && pwd )"
OUT="${ROOT}/dist/bench"
mkdir -p "${OUT}"

DO_PRECISION=0
BENCH_FILTER=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --precision|--with-precision)
      DO_PRECISION=1
      shift
      ;;
    --bench-filter)
      shift
      BENCH_FILTER="${1:-}"
      [[ $# -gt 0 ]] && shift
      ;;
    -h|--help)
      sed -n '2,21p' "$0"
      exit 0
      ;;
    *)
      shift
      ;;
  esac
done

hdr()  { printf "\n\033[1;36m=== %s ===\033[0m\n" "$*"; }
ok()   { printf "  \033[32m[OK]\033[0m   %s\n" "$*"; }
err()  { printf "  \033[31m[FAIL]\033[0m %s\n" "$*"; }
warn() { printf "  \033[33m[WARN]\033[0m %s\n" "$*"; }
info() { printf "  \033[36m[INFO]\033[0m %s\n" "$*"; }

# ---- 1. TA-Lib C detection -----------------------------------------------
hdr "[bench-vs-talib] step 1/4: detect TA-Lib C"
if pkg-config --exists ta-lib 2>/dev/null; then
  ok "TA-Lib C found via pkg-config: $(pkg-config --modversion ta-lib)"
else
  warn "TA-Lib C not found; attempting install"
  case "$( uname -s )" in
    MINGW*|MSYS*|CYGWIN*)
      warn "Windows detected."
      warn "Please download ta-lib-0.6.4-windows-x86_64.zip from"
      warn "  https://github.com/ta-lib/ta-lib/releases"
      warn "and extract to C:\\ta-lib, then set TA_LIBRARY_PATH=C:\\ta-lib\\lib"
      warn "and TA_INCLUDE_PATH=C:\\ta-lib\\include."
      if [[ -d "C:/ta-lib" ]]; then
        export TA_LIBRARY_PATH="C:/ta-lib/lib"
        export TA_INCLUDE_PATH="C:/ta-lib/include"
        ok "Found C:\\ta-lib; continuing with env hints"
      else
        err "no TA-Lib on Windows; cannot continue"
        exit 1
      fi
      ;;
    Darwin)
      if command -v brew >/dev/null 2>&1; then
        brew install ta-lib || { err "brew install ta-lib failed"; exit 1; }
      else
        err "no Homebrew; install TA-Lib manually"; exit 1
      fi
      ;;
    Linux)
      if command -v apt-get >/dev/null 2>&1; then
        sudo apt-get install -y libta-lib0-dev || {
          err "apt install failed; install TA-Lib manually"; exit 1;
        }
      else
        err "no apt-get; install TA-Lib manually"; exit 1
      fi
      ;;
    *)
      err "unsupported platform: $( uname -s )"; exit 1 ;;
  esac
fi

# ---- 2. cargo bench --------------------------------------------------------
hdr "[bench-vs-talib] step 2/4: cargo bench --features talib-c"
cd "${ROOT}/core"
if [[ -n "${BENCH_FILTER}" ]]; then
  cargo bench --bench talib_c_comparison --features talib-c -- "${BENCH_FILTER}"
else
  cargo bench --bench talib_c_comparison --features talib-c
fi
cd "${ROOT}"

# ---- 3. parse Criterion JSON + emit reports ------------------------------
hdr "[bench-vs-talib] step 3/4: bench_report.py -> markdown + JSON"
JSON_OUT="${OUT}/results.json"
python3 "${SCRIPT_DIR}/bench_report.py" \
    --criterion-dir "${ROOT}/target/criterion" \
    --output       "${OUT}/alpha-ta-vs-talib.md" \
    --json-out     "${JSON_OUT}"

# ---- 4. compact summary table --------------------------------------------
hdr "[bench-vs-talib] step 4/4: render dist/bench/summary.md"
python3 - <<PY > "${OUT}/summary.md"
import json, pathlib, datetime
res_path = pathlib.Path("${JSON_OUT}")
res = json.loads(res_path.read_text())
generated = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

print(f"# AlphaTA vs TA-Lib C — Head-to-Head Summary")
print()
print(f"> Auto-generated by \`scripts/bench-vs-talib.sh\` on {generated}")
print()
print("| Indicator | Category | AlphaTA (us) | TA-Lib C (us) | Speedup | Δ (pp) | Status |")
print("|---|---|---|---|---|---|---|")

bench = res.get("benchmarks", {})
order = sorted(bench.keys())
for k in order:
    v = bench[k]
    delta = v.get("delta_pp")
    delta_s = "—" if delta is None else f"{delta:.2e}"
    print(f"| {k} | {v.get('category', '?')} | {v['fta_us']:.2f} | "
          f"{v['talib_us']:.2f} | {v['speedup']:.2f}x | {delta_s} | {v['status']} |")

print()
total = len(bench)
faster = sum(1 for v in bench.values() if v['status'] == "✅")
slower = sum(1 for v in bench.values() if v['status'] == "❌")
warn_n = sum(1 for v in bench.values() if v['status'] == "⚠️")
print(f"- **Total**: {total}")
print(f"- **AlphaTA faster**: {faster}")
print(f"- **AlphaTA within 25%**: {warn_n}")
print(f"- **AlphaTA >25% slower**: {slower}")
PY
ok "summary written to ${OUT}/summary.md"

# ---- 5. optional precision parity ----------------------------------------
if [[ "${DO_PRECISION}" -eq 1 ]]; then
  hdr "[bench-vs-talib] step 5/5: precision parity (bench_vs_talib_precision.py)"
  if python3 "${SCRIPT_DIR}/bench_vs_talib_precision.py" \
        --json-out "${OUT}/precision.json" \
        --results  "${JSON_OUT}" \
        --output   "${OUT}/precision.md"; then
    ok "precision data merged into ${JSON_OUT}"
  else
    warn "precision step failed (likely missing AlphaTA or talib PyPI package);"
    warn "continuing without precision"
  fi
fi

# ---- done ----------------------------------------------------------------
hdr "[bench-vs-talib] DONE"
ls -lh "${OUT}/"
