#!/usr/bin/env python3
"""Generate triple comparison benchmark Markdown report from Criterion JSON output.

Compares Native Rust, Formula Engine (eval), Formula Engine (builtin),
and Formula Engine (zero_alloc) execution paths for each indicator.

Usage:
    python scripts/gen_triple_comparison_report.py [--target-dir TARGET_DIR] [--output OUTPUT]

Reads Criterion benchmark results from target/criterion/ and generates
a Markdown table with execution times (us), ratio (Formula/Native), and verdict.
"""

import argparse
import json
import os
import sys
from pathlib import Path

INDICATORS = [
    ("SMA(20)", "triple_SMA_20", "MA(CLOSE, 20)"),
    ("EMA(12)", "triple_EMA_12", "EMA(CLOSE, 12)"),
    ("WMA(20)", "triple_WMA_20", "WMA(CLOSE, 20)"),
    ("DEMA(10)", "triple_DEMA_10", "DEMA(CLOSE, 10)"),
    ("TEMA(10)", "triple_TEMA_10", "TEMA(CLOSE, 10)"),
    ("KAMA(10)", "triple_KAMA_10", "KAMA(CLOSE, 10)"),
    ("RSI(14)", "triple_RSI_14", "RSI(CLOSE, 14)"),
    ("MACD(12,26,9)", "triple_MACD", "MACD(C,12,26)"),
    ("CCI(14)", "triple_CCI_14", "CCI(H,L,C,14)"),
    ("ADX(14)", "triple_ADX_14", "ADX(H,L,C,14)"),
    ("ATR(14)", "triple_ATR_14", "ATR_ENHANCED(H,L,C,14)"),
    ("BBANDS(20,2)", "triple_BBANDS", "BOLL(C,20,2)"),
    ("STOCH(14,3)", "triple_STOCH", "STOCH(H,L,C,14,3,3)"),
    ("WILLR(14)", "triple_WILLR_14", "WILLR(H,L,C,14)"),
    ("ROC(10)", "triple_ROC_10", "ROC(CLOSE, 10)"),
    ("MOM(10)", "triple_MOM_10", "MOM(CLOSE, 10)"),
    ("STDDEV(20)", "triple_STDDEV", "STD(CLOSE, 20)"),
    ("LINEAR_REG(14)", "triple_Linear_Reg_14", "LINEARREG(CLOSE, 14)"),
    ("TRIX(14)", "triple_TRIX_14", "TRIX(CLOSE, 14)"),
]

SIZES = [10000, 100000, 1000000]

SIZE_LABELS = {
    10000: "10K",
    100000: "100K",
    1000000: "1M",
}

MODES = ["native", "formula_eval", "formula_builtin", "formula_zero_alloc"]

MODE_LABELS = {
    "native": "Native",
    "formula_eval": "Formula(eval)",
    "formula_builtin": "Formula(builtin)",
    "formula_zero_alloc": "Formula(zero_alloc)",
}


def find_criterion_result(target_dir: Path, group_name: str, mode: str, size: int) -> dict | None:
    pattern_parts = [group_name, mode, str(size)]
    estimates_path = target_dir / "criterion" / "/".join(pattern_parts) / "new" / "estimates.json"
    if estimates_path.exists():
        with open(estimates_path) as f:
            return json.load(f)

    for dirpath, _, filenames in os.walk(target_dir / "criterion"):
        if "estimates.json" in filenames:
            dir_str = dirpath.replace("\\", "/")
            if group_name in dir_str and mode in dir_str and str(size) in dir_str:
                with open(os.path.join(dirpath, "estimates.json")) as f:
                    return json.load(f)
    return None


def get_mean_us(estimates: dict) -> float:
    mean_ns = estimates["mean"]["point_estimate"]
    return mean_ns / 1000.0


def verdict(ratio: float) -> str:
    if ratio < 1.0:
        return "\U0001f7e2 \u8d85\u8d8a"
    elif ratio <= 1.2:
        return "\U0001f7e1 \u6301\u5e73"
    else:
        return "\U0001f534 \u843d\u540e"


def generate_report(target_dir: Path) -> str:
    lines = []
    lines.append("# Triple Comparison Benchmark Report")
    lines.append("")
    lines.append("> Auto-generated by `scripts/gen_triple_comparison_report.py`")
    lines.append(">")
    lines.append("> Compares: **Native Rust** | **Formula(eval)** | **Formula(builtin)** | **Formula(zero_alloc)**")
    lines.append("")
    lines.append("---")
    lines.append("")

    for size in SIZES:
        label = SIZE_LABELS[size]
        lines.append(f"## Data Size: {label} ({size:,} bars)")
        lines.append("")

        header = (
            "| Indicator | Native (\u00b5s) | Formula(eval) (\u00b5s) | "
            "Formula(builtin) (\u00b5s) | Formula(zero_alloc) (\u00b5s) | "
            "eval/Native | builtin/Native | zero_alloc/Native | Verdict |"
        )
        sep = (
            "|-----------|--------------:|---------------------:|"
            "-----------------------:|---------------------------:|"
            "-----------:|-------------:|------------------:|---------|"
        )
        lines.append(header)
        lines.append(sep)

        for ind_name, group_name, _formula in INDICATORS:
            native_est = find_criterion_result(target_dir, group_name, "native", size)
            eval_est = find_criterion_result(target_dir, group_name, "formula_eval", size)
            builtin_est = find_criterion_result(target_dir, group_name, "formula_builtin", size)
            zero_alloc_est = find_criterion_result(target_dir, group_name, "formula_zero_alloc", size)

            if native_est is None:
                lines.append(f"| {ind_name} | (not run) | - | - | - | - | - | - | - |")
                continue

            native_us = get_mean_us(native_est)
            eval_us = get_mean_us(eval_est) if eval_est else None
            builtin_us = get_mean_us(builtin_est) if builtin_est else None
            zero_alloc_us = get_mean_us(zero_alloc_est) if zero_alloc_est else None

            eval_str = f"{eval_us:.1f}" if eval_us is not None else "-"
            builtin_str = f"{builtin_us:.1f}" if builtin_us is not None else "-"
            zero_alloc_str = f"{zero_alloc_us:.1f}" if zero_alloc_us is not None else '-'

            eval_ratio = (eval_us / native_us) if eval_us is not None else None
            builtin_ratio = (builtin_us / native_us) if builtin_us is not None else None
            zero_alloc_ratio = (zero_alloc_us / native_us) if zero_alloc_us is not None else None

            eval_ratio_str = f"{eval_ratio:.2f}x" if eval_ratio is not None else "-"
            builtin_ratio_str = f"{builtin_ratio:.2f}x" if builtin_ratio is not None else "-"
            zero_alloc_ratio_str = f"{zero_alloc_ratio:.2f}x" if zero_alloc_ratio is not None else "-"

            best_ratio = None
            for r in [eval_ratio, builtin_ratio, zero_alloc_ratio]:
                if r is not None:
                    if best_ratio is None or r < best_ratio:
                        best_ratio = r

            verdict_str = verdict(best_ratio) if best_ratio is not None else "-"

            lines.append(
                f"| {ind_name} | {native_us:.1f} | {eval_str} | {builtin_str} | "
                f"{zero_alloc_str} | {eval_ratio_str} | {builtin_ratio_str} | "
                f"{zero_alloc_ratio_str} | {verdict_str} |"
            )

        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("## How to Reproduce")
    lines.append("")
    lines.append("```bash")
    lines.append("cargo bench --bench talib_triple_comparison_bench")
    lines.append("python scripts/gen_triple_comparison_report.py")
    lines.append("```")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate triple comparison benchmark report"
    )
    parser.add_argument(
        "--target-dir",
        default="target",
        help="Cargo target directory (default: target)",
    )
    parser.add_argument(
        "--output",
        default="docs/triple-comparison-benchmark.md",
        help="Output file path (default: docs/triple-comparison-benchmark.md)",
    )
    args = parser.parse_args()

    target_dir = Path(args.target_dir)

    if not (target_dir / "criterion").exists():
        print(
            f"Warning: {target_dir / 'criterion'} not found. "
            "Run `cargo bench --bench talib_triple_comparison_bench` first.",
            file=sys.stderr,
        )
        print("Generating report with placeholder data...", file=sys.stderr)

    report = generate_report(target_dir)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report, encoding="utf-8")
    print(f"Report written to {output_path}")


if __name__ == "__main__":
    main()
