#!/usr/bin/env python3
"""
Generate golden test input data for finkit-core.

Reference indicator values are produced via self-golden: the Rust integration
test `generate_golden` (ignored by default) computes values with our library
and writes CSVs under tests/golden/. Run:

    cargo test -p finkit --test golden_tests generate_golden -- --ignored

This script only generates the deterministic OHLCV input series so the
workspace has reproducible fixtures without requiring TA-Lib or numpy.
"""

from __future__ import annotations

import csv
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GOLDEN_DIR = ROOT / "tests" / "golden"


def generate_ohlcv(rows: int = 50) -> list[tuple[float, float, float, float, float]]:
    data: list[tuple[float, float, float, float, float]] = []
    for i in range(rows):
        base = 40000 + i * 50 + 500 * math.sin(i * 0.3)
        open_p = base
        high_p = base + 200 + 50 * abs(math.sin(i * 0.7))
        low_p = base - 200 - 50 * abs(math.cos(i * 0.7))
        close_p = base + 100 * math.sin(i * 0.5)
        volume = 100000 + 50000 * abs(math.sin(i * 0.2))
        data.append((open_p, high_p, low_p, close_p, volume))
    return data


def write_input_csv(path: Path, data: list[tuple[float, float, float, float, float]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["open", "high", "low", "close", "volume"])
        for row in data:
            writer.writerow([f"{v:.17g}" for v in row])


def main() -> None:
    write_input_csv(GOLDEN_DIR / "input_ohlcv.csv", generate_ohlcv())
    print(f"Wrote {GOLDEN_DIR / 'input_ohlcv.csv'}")
    print(
        "Indicator reference CSVs are generated by Rust (self-golden). Run:\n"
        "  cargo test -p finkit --test golden_tests generate_golden -- --ignored"
    )


if __name__ == "__main__":
    main()
