//! Contract test for the four-terminal formula dialect coverage matrix.
//!
//! `tests/contracts/formula_dialect_coverage_v1.json` is generated by
//! `scripts/gen_dialect_coverage.py`. This gate keeps the contract honest in
//! the directions that matter:
//!
//! 1. **Statuses must agree with the runtime.** `exact`/`near`/`approximate`
//!    claim a name runs out of the box, so the engine must register it;
//!    `unsupported` claims it does not, so the engine must not. `host_required`
//!    is the *reason* a name is not out-of-the-box coverage (the host must
//!    inject market/session data) and deliberately makes no registration claim.
//! 2. **`registered` is a machine fact.** It is re-derived from the live
//!    function table, so a row cannot claim a registration that does not exist.
//!    This is the check that caught `REFX` being credited as coverage.
//! 3. **Provenance is substantiated, not asserted.** Every row tagged
//!    `repo:*` must actually contain its reference name in the file the tag
//!    points at. Hand-written traceability is what produced five false
//!    `repo:functions_legacy` tags before this gate existed.
//! 4. **The corpus must live inside the claimed coverage.** Every function a
//!    checked-in corpus formula calls must not be `unsupported`.
//! 5. **`corpus_exercised` is derived, not asserted.** Which rows a checked-in
//!    corpus actually calls is recomputed here from the corpus files. A row can
//!    be `registered` without being exercised, and the contract has to say so
//!    rather than let registration stand in for a runnable test.
//! 6. **The Pine mapping is proved against the mapper, not mirrored.** The
//!    canonical name a Pine `ta.*` spelling reaches is decided by three
//!    different pieces of `ast_mapper.rs` (hard-coded `ta.*` special cases, a
//!    builtin table, and a `TA_<NAME>` / `MATH_<NAME>` fallback). The generator
//!    used to keep a fourth, hand-written copy of that mapping, which drifted
//!    silently -- the corpus was green because it happened to only use
//!    spellings all four copies agreed on. `pine_engine_mapping` in the contract
//!    now records what the engine emits, and
//!    [`pine_engine_mapping_matches_the_engine`] lowers every spelling through
//!    `map_pine_to_alphata` to prove it.

mod common;

use finkit::formula::pine::{map_pine_to_alphata, parse_pine};
use finkit::formula::AstNode;
use serde::Deserialize;
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

const CONTRACT: &str = "tests/contracts/formula_dialect_coverage_v1.json";
const CORPUS_DIR: &str = "tests/formula_corpus";
const PINE_CORPUS_DIR: &str = "tests/pine_corpus";
const CLASSIC_SOURCE: &str = "repo:talib_coverage_matrix";

/// Floor for `corpus_exercised` across the terminals that supply it (measured
/// 70 on 2026-09-23: `tongdaxin` 42, `tonghuashun` 3, `dazhihui` 2,
/// `tradingview_pine` 23). A floor rather than an equality: adding corpus
/// coverage must stay easy, while silently losing it must not.
const MIN_CORPUS_EXERCISED: usize = 65;

#[derive(Debug, Deserialize)]
struct Contract {
    schema_version: u32,
    generated_by: String,
    collected: String,
    statuses: Vec<String>,
    runtime_formula_surface: usize,
    /// Tag -> repository-relative path. Declared by the generator so this gate
    /// can substantiate provenance without duplicating the mapping.
    provenance_sources: BTreeMap<String, String>,
    /// Vendor function lists. Not files, so they can only ever explain an
    /// `attributed` row; declaring them keeps the tag vocabulary closed.
    vendor_sources: BTreeMap<String, String>,
    terminals: BTreeMap<String, Terminal>,
    unverified_candidates: BTreeMap<String, Vec<String>>,
    /// Which corpora supply `corpus_exercised`, and what each contributed.
    corpus_sources: BTreeMap<String, CorpusSource>,
    /// Pine spelling -> the canonical name `map_pine_to_alphata` emits.
    ///
    /// Total: a spelling the builtin table does not resolve still lands on the
    /// `TA_<NAME>` / `MATH_<NAME>` fallback. Recorded in the contract so the
    /// gate can prove the mapping behaviourally instead of trusting the
    /// generator's reading of three separate code paths.
    pine_engine_mapping: BTreeMap<String, String>,
}

#[derive(Debug, Deserialize)]
struct CorpusSource {
    kind: String,
    cases: usize,
    terminals: Vec<String>,
    /// `Some("corpus_exercised")` when this corpus produces row-level evidence;
    /// `None` when it is deliberately withheld (with `deferred_reason` set).
    row_level_evidence: Option<String>,
    deferred_reason: Option<String>,
}

#[derive(Debug, Deserialize)]
struct Terminal {
    id: String,
    label: String,
    reference: String,
    collected: String,
    reference_size: usize,
    verified_size: usize,
    attributed_size: usize,
    functions: BTreeMap<String, Entry>,
    coverage: BTreeMap<String, usize>,
    coverage_pct: f64,
    verified_coverage_pct: f64,
    registered: usize,
    host_dependent_registered: Vec<String>,
    /// Corpus cases attributed to this terminal.
    corpus_cases: usize,
    /// Rows a checked-in corpus case actually calls, derived by the generator
    /// and recomputed by [`corpus_evidence_is_derived_from_the_corpora`].
    ///
    /// `None` means row-level evidence is deliberately withheld for this
    /// terminal; `corpus_sources` must then carry a `deferred_reason`. The two
    /// cases are kept distinct on purpose: an absent field is a documented
    /// deferral, an empty list would be an ambiguous "measured nothing".
    corpus_exercised: Option<Vec<String>>,
}

#[derive(Debug, Deserialize)]
struct Entry {
    status: String,
    /// Machine fact: is the name in the engine's function table?
    registered: bool,
    source: String,
    /// `verified` (found in a named in-repo file) or `attributed` (a vendor
    /// function list this repository cannot read).
    provenance: String,
    /// The token that substantiated the row, when it differs from the
    /// canonical name (a Pine `ta.*` spelling, say).
    via: Option<String>,
}

#[derive(Debug, Deserialize)]
struct CorpusCase {
    id: String,
    platform: String,
    source_formula: String,
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..")
}

fn load_contract() -> Contract {
    let path = workspace_root().join(CONTRACT);
    let raw = fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
    serde_json::from_str(&raw).expect("parse dialect coverage contract")
}

/// Platform tag in `tests/formula_corpus/*.json` -> contract terminal key.
fn terminal_for_platform(platform: &str) -> &'static str {
    match platform.to_ascii_lowercase().as_str() {
        "tdx" | "cross" => "tongdaxin",
        "ths" => "tonghuashun",
        "dzh" => "dazhihui",
        "pine" | "tradingview" => "tradingview_pine",
        other => panic!("corpus platform {other} has no contract terminal"),
    }
}

/// Function names a formula source calls: `NAME(` at an identifier boundary.
fn called_functions(source: &str) -> BTreeSet<String> {
    let bytes = source.as_bytes();
    let mut names = BTreeSet::new();
    for (index, byte) in bytes.iter().enumerate() {
        if *byte != b'(' {
            continue;
        }
        let mut start = index;
        while start > 0 {
            let previous = bytes[start - 1];
            if previous.is_ascii_alphanumeric() || previous == b'_' {
                start -= 1;
            } else {
                break;
            }
        }
        if start == index {
            continue;
        }
        let candidate = &source[start..index];
        if candidate
            .chars()
            .next()
            .is_some_and(|first| first.is_ascii_alphabetic() || first == '_')
        {
            names.insert(candidate.to_ascii_uppercase());
        }
    }
    names
}

fn corpus_cases() -> Vec<CorpusCase> {
    let root = workspace_root().join(CORPUS_DIR);
    let mut paths: Vec<PathBuf> = fs::read_dir(&root)
        .unwrap_or_else(|error| panic!("read {}: {error}", root.display()))
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().is_some_and(|ext| ext == "json"))
        .collect();
    paths.sort();
    paths
        .iter()
        .map(|path| {
            let raw = fs::read_to_string(path).expect("read corpus case");
            serde_json::from_str(&raw)
                .unwrap_or_else(|error| panic!("parse {}: {error}", path.display()))
        })
        .collect()
}

/// Whole-token containment: `COG` must not be substantiated by `COGS`.
fn contains_token(text: &str, token: &str) -> bool {
    let bytes = text.as_bytes();
    let needle = token.as_bytes();
    if needle.is_empty() || needle.len() > bytes.len() {
        return false;
    }
    let is_word = |b: u8| b.is_ascii_alphanumeric() || b == b'_';
    for start in 0..=(bytes.len() - needle.len()) {
        if &bytes[start..start + needle.len()] != needle {
            continue;
        }
        let before_ok = start == 0 || !is_word(bytes[start - 1]);
        let end = start + needle.len();
        let after_ok = end == bytes.len() || !is_word(bytes[end]);
        if before_ok && after_ok {
            return true;
        }
    }
    false
}

#[test]
fn contract_is_self_consistent_and_covers_four_terminals() {
    let contract = load_contract();
    assert_eq!(contract.schema_version, 1);
    assert_eq!(contract.generated_by, "scripts/gen_dialect_coverage.py");
    assert!(!contract.collected.is_empty());
    assert!(
        contract.runtime_formula_surface > 0,
        "contract must record the runtime formula surface it was built against"
    );

    let expected: BTreeSet<&str> = ["tongdaxin", "tonghuashun", "dazhihui", "tradingview_pine"]
        .into_iter()
        .collect();
    let actual: BTreeSet<&str> = contract.terminals.keys().map(String::as_str).collect();
    assert_eq!(actual, expected, "terminal set changed");

    let statuses: BTreeSet<&str> = contract.statuses.iter().map(String::as_str).collect();
    assert_eq!(
        statuses,
        BTreeSet::from([
            "exact",
            "near",
            "approximate",
            "host_required",
            "unsupported"
        ]),
        "the five-state vocabulary is part of the contract"
    );

    for (key, terminal) in &contract.terminals {
        assert!(
            terminal.reference_size >= 200,
            "{key}: reference list is only {} entries",
            terminal.reference_size
        );
        assert_eq!(
            terminal.functions.len(),
            terminal.reference_size,
            "{key}: reference_size disagrees with the function table"
        );
        assert_eq!(
            terminal.verified_size + terminal.attributed_size,
            terminal.reference_size,
            "{key}: verified + attributed must account for every row"
        );
        assert_eq!(
            terminal.collected, contract.collected,
            "{key}: terminals were collected on different dates"
        );
        assert!(
            !terminal.reference.is_empty() && !terminal.label.is_empty(),
            "{key}: every terminal must name its reference and label"
        );

        // Recompute every aggregate from the rows instead of trusting it.
        let mut recomputed: BTreeMap<&str, usize> =
            contract.statuses.iter().map(|s| (s.as_str(), 0)).collect();
        let mut registered = 0usize;
        let mut verified = 0usize;
        let mut host_dependent_registered = Vec::new();
        let mut out_of_the_box = 0usize;
        let mut out_of_the_box_verified = 0usize;
        for (name, entry) in &terminal.functions {
            assert!(
                contract.statuses.contains(&entry.status),
                "{key}/{name}: unknown status {}",
                entry.status
            );
            let declared = if entry.source.starts_with("vendor:") {
                contract.vendor_sources.contains_key(&entry.source)
            } else {
                contract.provenance_sources.contains_key(&entry.source)
            };
            assert!(
                declared,
                "{key}/{name}: source `{}` is not a declared provenance tag",
                entry.source
            );
            assert!(
                matches!(entry.provenance.as_str(), "verified" | "attributed"),
                "{key}/{name}: unknown provenance {}",
                entry.provenance
            );
            // A `repo:` tag is only ever allowed on a substantiated row; if we
            // cannot read the file, the row must fall back to `vendor:`.
            match entry.provenance.as_str() {
                "attributed" => assert!(
                    entry.source.starts_with("vendor:"),
                    "{key}/{name}: `{}` is attributed but is not a vendor source",
                    entry.source
                ),
                "verified" => assert!(
                    !entry.source.starts_with("vendor:"),
                    "{key}/{name}: `{}` claims verification by a vendor list",
                    entry.source
                ),
                _ => {}
            }
            *recomputed.entry(entry.status.as_str()).or_default() += 1;
            if entry.registered {
                registered += 1;
            }
            if entry.provenance == "verified" {
                verified += 1;
            }
            if entry.status == "host_required" && entry.registered {
                host_dependent_registered.push(name.clone());
            }
            let runs = matches!(entry.status.as_str(), "exact" | "near" | "approximate");
            if runs {
                out_of_the_box += 1;
                if entry.provenance == "verified" {
                    out_of_the_box_verified += 1;
                }
            }
        }
        for status in &contract.statuses {
            assert_eq!(
                terminal.coverage.get(status).copied().unwrap_or(0),
                recomputed[status.as_str()],
                "{key}: coverage[{status}] does not match the rows"
            );
        }
        assert_eq!(
            terminal.registered, registered,
            "{key}: registered count does not match the rows"
        );
        assert_eq!(
            terminal.verified_size, verified,
            "{key}: verified_size does not match the rows"
        );
        assert_eq!(
            terminal.host_dependent_registered, host_dependent_registered,
            "{key}: host_dependent_registered does not match the rows"
        );
        let pct = |numerator: usize, denominator: usize| -> f64 {
            if denominator == 0 {
                0.0
            } else {
                (1000.0 * numerator as f64 / denominator as f64).round() / 10.0
            }
        };
        assert!(
            (terminal.coverage_pct - pct(out_of_the_box, terminal.reference_size)).abs() < 0.05,
            "{key}: coverage_pct {} does not match the rows",
            terminal.coverage_pct
        );
        assert!(
            (terminal.verified_coverage_pct - pct(out_of_the_box_verified, terminal.verified_size))
                .abs()
                < 0.05,
            "{key}: verified_coverage_pct {} does not match the rows",
            terminal.verified_coverage_pct
        );
        assert!(
            terminal.registered >= out_of_the_box,
            "{key}: {registered} registered rows cannot be fewer than the \
             {out_of_the_box} out-of-the-box rows"
        );
    }

    // A dropped name must not also appear as a row: the contract reports the
    // unsourced surface separately instead of laundering it into a percentage.
    for (key, names) in &contract.unverified_candidates {
        let terminal = contract
            .terminals
            .get(key)
            .unwrap_or_else(|| panic!("unverified_candidates names an unknown terminal {key}"));
        for name in names {
            assert!(
                !terminal.functions.contains_key(name),
                "{key}/{name}: reported as unverified but also counted as a row"
            );
        }
    }
}

/// Every `repo:*` row must actually be substantiated by the file it cites.
///
/// This is the assertion that makes the contract's central promise -- "every
/// reference name is traceable to a named source" -- mechanically true rather
/// than a claim the generator makes about itself.
#[test]
fn every_verified_provenance_tag_is_substantiated() {
    let contract = load_contract();
    let mut checked = 0usize;
    let mut problems = Vec::new();

    for (key, terminal) in &contract.terminals {
        for (name, entry) in &terminal.functions {
            if entry.provenance != "verified" {
                continue;
            }
            let Some(relative) = contract.provenance_sources.get(&entry.source) else {
                problems.push(format!("{key}/{name}: undeclared source {}", entry.source));
                continue;
            };
            let path = workspace_root().join(relative);
            let text = fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
            // A Pine row is substantiated by its `ta.*` spelling rather than by
            // the canonical name it maps to.
            let token = entry.via.as_deref().unwrap_or(name.as_str());
            if !contains_token(&text, token) {
                problems.push(format!(
                    "{key}/{name}: `{token}` not found in {relative}, so `{}` is unsubstantiated",
                    entry.source
                ));
            }
            checked += 1;
        }
    }

    assert!(
        problems.is_empty(),
        "provenance tags are not substantiated:\n{}",
        problems.join("\n")
    );
    assert!(
        checked >= 800,
        "only {checked} rows carry substantiated provenance; the contract has \
         regressed to hand-written traceability"
    );
    assert!(
        !contract.provenance_sources.is_empty()
            && contract.provenance_sources.contains_key(CLASSIC_SOURCE),
        "the classic TA core must be substantiated by the coverage matrix"
    );
}

#[test]
fn contract_statuses_agree_with_the_runtime_formula_table() {
    let contract = load_contract();
    let runtime = finkit::formula::functions::get_builtin_functions();

    let mut problems = Vec::new();
    for (key, terminal) in &contract.terminals {
        for (name, entry) in &terminal.functions {
            let callable = runtime.contains_key(name.as_str());

            // `registered` is a machine fact and must match the live engine
            // exactly. This is the check that catches a row claiming a
            // registration that does not exist.
            if entry.registered != callable {
                problems.push(format!(
                    "{key}/{name}: `registered` says {} but the engine says {callable}",
                    entry.registered
                ));
            }

            match entry.status.as_str() {
                "exact" | "near" | "approximate" => {
                    if !callable {
                        problems.push(format!(
                            "{key}/{name}: claimed `{}` (out of the box) but the \
                             engine registers no implementation",
                            entry.status
                        ));
                    }
                }
                "unsupported" => {
                    if callable {
                        problems.push(format!(
                            "{key}/{name}: claimed `unsupported` but the runtime \
                             registers it"
                        ));
                    }
                }
                // The reason for non-coverage; makes no registration claim.
                "host_required" => {}
                other => problems.push(format!("{key}/{name}: unknown status {other}")),
            }
        }
    }
    assert!(
        problems.is_empty(),
        "dialect contract disagrees with the runtime:\n{}",
        problems.join("\n")
    );
}

/// Every `*.pine` script in the Pine corpus, sorted for a stable order.
fn pine_corpus_paths() -> Vec<PathBuf> {
    let root = workspace_root().join(PINE_CORPUS_DIR);
    let mut paths: Vec<PathBuf> = fs::read_dir(&root)
        .unwrap_or_else(|error| panic!("read {}: {error}", root.display()))
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().is_some_and(|ext| ext == "pine"))
        .collect();
    paths.sort();
    paths
}

/// Number of `*.pine` scripts in the Pine corpus.
///
/// Gating the count catches the corpus being deleted or silently emptied.
fn pine_corpus_script_count() -> usize {
    pine_corpus_paths().len()
}

/// `ta.<name>` / `math.<name>` spellings a Pine source calls.
///
/// The generator resolves these through the same mapping, so the two agree by
/// construction rather than by convention.
fn namespaced_calls(source: &str) -> BTreeSet<String> {
    /// Walk back over `[A-Za-z0-9_]`, returning the start index.
    fn ident_start(source: &str, from: usize) -> usize {
        let bytes = source.as_bytes();
        let mut start = from;
        while start > 0 {
            let previous = bytes[start - 1];
            if previous.is_ascii_alphanumeric() || previous == b'_' {
                start -= 1;
            } else {
                break;
            }
        }
        start
    }

    let bytes = source.as_bytes();
    let mut names = BTreeSet::new();
    for (index, byte) in bytes.iter().enumerate() {
        if *byte != b'(' {
            continue;
        }
        let name_start = ident_start(source, index);
        // The namespace must be preceded by a dot, and that dot by a bare
        // `ta` / `math` at an identifier boundary.
        if name_start == 0 || bytes[name_start - 1] != b'.' {
            continue;
        }
        let namespace_start = ident_start(source, name_start - 1);
        let namespace = &source[namespace_start..name_start - 1];
        if !matches!(namespace, "ta" | "math") {
            continue;
        }
        let name = &source[name_start..index];
        if !name.is_empty()
            && name
                .bytes()
                .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_')
        {
            names.insert(source[namespace_start..index].to_string());
        }
    }
    names
}

/// Which Pine rows the corpus reaches, resolved through the engine mapping.
///
/// A Pine `ta.*` call reaches a contract row only via `pine_engine_mapping`, so
/// the evidence has to be resolved rather than matched by identity. The mapping
/// itself is proved by [`pine_engine_mapping_matches_the_engine`].
fn pine_exercised(contract: &Contract) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    for path in pine_corpus_paths() {
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
        for spelling in namespaced_calls(&source) {
            if let Some(canonical) = contract.pine_engine_mapping.get(&spelling) {
                names.insert(canonical.clone());
            }
        }
    }
    names
}

/// A row claiming `exact` must also be covered by a runnable case.
///
/// No row makes that claim today, so this passes vacuously. It is written out
/// anyway because the alternative -- adding `exact` rows later with no test
/// behind them -- is exactly the "promise without a gate" shape this project
/// keeps finding in its own contracts.
fn assert_exact_rows_are_exercised(contract: &Contract) {
    for (key, terminal) in &contract.terminals {
        let Some(names) = terminal.corpus_exercised.as_ref() else {
            continue;
        };
        let exercised: BTreeSet<&str> = names.iter().map(String::as_str).collect();
        let uncovered: Vec<&str> = terminal
            .functions
            .iter()
            .filter(|(name, entry)| entry.status == "exact" && !exercised.contains(name.as_str()))
            .map(|(name, _)| name.as_str())
            .collect();
        assert!(
            uncovered.is_empty(),
            "{key}: `exact` rows with no corpus coverage: {uncovered:?}"
        );
    }
}

/// Split `corpus_sources` into the terminals that supply row-level evidence and
/// the ones that withhold it.
///
/// A withheld `corpus_exercised` is only acceptable when a corpus source says so
/// and gives a reason. Otherwise "no evidence" and "not measured" would be
/// indistinguishable -- the ambiguity this field exists to avoid.
fn corpus_source_roles(contract: &Contract) -> (BTreeSet<&str>, BTreeSet<&str>) {
    let mut deferred: BTreeSet<&str> = BTreeSet::new();
    let mut supplied: BTreeSet<&str> = BTreeSet::new();
    for (dir, source) in &contract.corpus_sources {
        assert!(
            !source.kind.is_empty() && source.cases > 0,
            "{dir}: a corpus source must declare its kind and a non-zero case count"
        );
        match source.row_level_evidence.as_deref() {
            Some("corpus_exercised") => {
                supplied.extend(source.terminals.iter().map(String::as_str));
            }
            Some(other) => panic!("{dir}: unknown row_level_evidence {other:?}"),
            None => {
                assert!(
                    source
                        .deferred_reason
                        .as_deref()
                        .is_some_and(|reason| !reason.is_empty()),
                    "{dir}: withholding row-level evidence requires a deferred_reason"
                );
                deferred.extend(source.terminals.iter().map(String::as_str));
            }
        }
    }
    (supplied, deferred)
}

/// Which reference rows the checked-in corpora actually call, recomputed here.
///
/// [`contract_statuses_agree_with_the_runtime_formula_table`] proves a row is
/// *registered*. This proves a row is *exercised*, which is the weaker claim's
/// stronger sibling: this repository has already shipped a `SIGN` whose three
/// implementations disagreed and a factor library that registered 175 factors
/// none of which could be evaluated, and in both cases registration was green.
///
/// The evidence is recomputed from the corpus files rather than read from the
/// contract, so the contract cannot claim test coverage it does not have.
#[test]
fn corpus_evidence_is_derived_from_the_corpora() {
    let contract = load_contract();
    let (supplied, deferred) = corpus_source_roles(&contract);

    // Recompute the domestic evidence from `tests/formula_corpus`.
    let mut recomputed: BTreeMap<&str, BTreeSet<String>> = BTreeMap::new();
    let mut cases: BTreeMap<&str, usize> = BTreeMap::new();
    for case in corpus_cases() {
        let key = terminal_for_platform(&case.platform);
        *cases.entry(key).or_default() += 1;
        recomputed
            .entry(key)
            .or_default()
            .extend(called_functions(&case.source_formula));
    }
    // A Pine `ta.*` call reaches a row only through the engine's mapping, so its
    // evidence is resolved rather than matched by identity.
    cases.insert("tradingview_pine", pine_corpus_script_count());
    recomputed.insert("tradingview_pine", pine_exercised(&contract));

    let mut total = 0usize;
    for (key, terminal) in &contract.terminals {
        assert_eq!(
            terminal.corpus_cases,
            cases.get(key.as_str()).copied().unwrap_or(0),
            "{key}: corpus_cases does not match the corpus directory"
        );
        let recorded = terminal.corpus_exercised.as_ref();
        let expected = recomputed.get(key.as_str());

        match recorded {
            Some(names) => {
                assert!(
                    supplied.contains(key.as_str()),
                    "{key}: records corpus_exercised but no corpus source supplies it"
                );
                let recorded: BTreeSet<&str> = names.iter().map(String::as_str).collect();
                let actual: BTreeSet<&str> = expected
                    .into_iter()
                    .flatten()
                    .map(String::as_str)
                    .filter(|name| terminal.functions.contains_key(*name))
                    .collect();
                assert_eq!(
                    recorded,
                    actual,
                    "{key}: corpus_exercised is not what the corpus calls \
                     (missing: {:?}, spurious: {:?})",
                    actual.difference(&recorded).collect::<Vec<_>>(),
                    recorded.difference(&actual).collect::<Vec<_>>()
                );
                // A row the corpus runs cannot be one the contract calls
                // unsupported; `corpus_formulas_stay_inside_the_claimed_coverage`
                // checks the same thing from the corpus side.
                for name in &recorded {
                    assert_ne!(
                        terminal.functions[*name].status, "unsupported",
                        "{key}/{name}: exercised by the corpus but marked unsupported"
                    );
                }
                total += recorded.len();
            }
            None => {
                assert!(
                    deferred.contains(key.as_str()),
                    "{key}: omits corpus_exercised without a deferred_reason"
                );
            }
        }
    }

    // The strongest claim in the vocabulary is `exact`. No row makes it today,
    // so this is a forward guard: the moment a row claims terminal-identical
    // numerics it must also be covered by a runnable case.
    assert_exact_rows_are_exercised(&contract);

    assert!(
        total >= MIN_CORPUS_EXERCISED,
        "only {total} corpus-exercised rows; expected at least {MIN_CORPUS_EXERCISED}"
    );
}

#[test]
fn corpus_formulas_stay_inside_the_claimed_coverage() {
    let contract = load_contract();
    let mut checked = 0usize;
    let mut problems = Vec::new();

    for case in corpus_cases() {
        let key = terminal_for_platform(&case.platform);
        let terminal = contract
            .terminals
            .get(key)
            .unwrap_or_else(|| panic!("{}: unknown terminal key {key}", case.id));
        for name in called_functions(&case.source_formula) {
            let Some(entry) = terminal.functions.get(&name) else {
                // Not part of this terminal's reference list: the contract makes
                // no claim about it, so the corpus is free to use it.
                continue;
            };
            checked += 1;
            if entry.status == "unsupported" {
                problems.push(format!(
                    "{} ({}): calls {name}, which the contract marks `unsupported`",
                    case.id, terminal.id
                ));
            }
        }
    }

    assert!(
        problems.is_empty(),
        "corpus uses functions outside the claimed coverage:\n{}",
        problems.join("\n")
    );
    assert!(
        checked >= 20,
        "corpus/contract overlap is only {checked} function references; \
         the corpus and the contract have drifted apart"
    );
}

// ---------------------------------------------------------------------------
// Pine mapping
// ---------------------------------------------------------------------------

/// Arguments used to probe a Pine spelling.
///
/// Built-in `ta.*` / `math.*` calls are mapped by *name*, not by arity: the
/// `ast_mapper.rs` special cases read only the argument positions they need and
/// the generic table path passes the rest straight through. One generous
/// argument list therefore probes every spelling without a per-function
/// signature table -- which is the point, since a hand-maintained signature
/// table is exactly what drifted in the first place.
const PINE_PROBE_ARGS: &str = "close, 14, 20, 9";

/// The one spelling whose mapping the *host* decides, not the builtin table.
///
/// `request.security` needs an explicit timeframe alignment, so `ast_mapper.rs`
/// refuses to resolve it from the table. The contract still records the name the
/// table would give -- and marks the row `host_required` -- but the gate has to
/// assert the refusal rather than a name.
const HOST_RESOLVED_SPELLING: &str = "request.security";

/// First `FunctionCall` in document order.
///
/// The probe script assigns one `<spelling>(<args>)` expression to one variable,
/// so the first call reached is the probe's own. The `indicator("Probe")`
/// declaration maps to a string literal rather than a call, so it contributes
/// nothing.
fn first_call_name(node: &AstNode) -> Option<&str> {
    match node {
        AstNode::FunctionCall { name, .. } => Some(name),
        AstNode::Statements(items) => items.iter().find_map(first_call_name),
        AstNode::Assignment { expr, .. }
        | AstNode::CompoundAssignment { expr, .. }
        | AstNode::Output { expr, .. }
        | AstNode::UnaryOp { expr, .. } => first_call_name(expr),
        AstNode::BinaryOp { left, right, .. } => {
            first_call_name(left).or_else(|| first_call_name(right))
        }
        AstNode::IndexAccess { array, .. } => first_call_name(array),
        _ => None,
    }
}

/// The contract's Pine mapping must be what `map_pine_to_alphata` actually does.
///
/// This is the gate that turns the mapping from a fourth, hand-written mirror
/// into a proved fact. Before it existed, the generator carried its own list of
/// canonical names; 48 of the 86 spellings it listed were never registered, and
/// the mismatch was invisible because the Pine corpus happened to call only the
/// spellings every copy agreed on. Recording the engine's behaviour and then
/// re-deriving it from the engine is what makes the coverage number honest.
#[test]
fn pine_engine_mapping_matches_the_engine() {
    let contract = load_contract();
    assert!(
        contract.pine_engine_mapping.len() >= 90,
        "the Pine mapping has shrunk to {} entries; the generator is no longer \
         reading the engine",
        contract.pine_engine_mapping.len()
    );

    let mut checked = 0usize;
    let mut host_resolved = Vec::new();
    for (spelling, expected) in &contract.pine_engine_mapping {
        let source =
            format!("//@version=5\nindicator(\"Probe\")\nprobe = {spelling}({PINE_PROBE_ARGS})\n");
        let pine = parse_pine(&source)
            .unwrap_or_else(|error| panic!("{spelling}: probe failed to parse: {error}"));

        if spelling == HOST_RESOLVED_SPELLING {
            let error = map_pine_to_alphata(&pine)
                .expect_err("request.security must not resolve without a host resolver");
            assert!(
                error.message.contains("host"),
                "{spelling}: expected a host-alignment error, got {}",
                error.message
            );
            host_resolved.push(spelling.as_str());
            continue;
        }

        let ast = map_pine_to_alphata(&pine)
            .unwrap_or_else(|error| panic!("{spelling}: failed to map: {error}"));
        let actual = first_call_name(&ast)
            .unwrap_or_else(|| panic!("{spelling}: probe produced no function call"));
        assert_eq!(
            actual, expected,
            "{spelling}: the contract records `{expected}` but the engine emits `{actual}`"
        );
        checked += 1;
    }

    assert_eq!(
        host_resolved,
        vec![HOST_RESOLVED_SPELLING],
        "the set of spellings that cannot be probed by name has changed"
    );
    assert!(
        checked >= 90,
        "only {checked} Pine spellings were proved against the engine"
    );

    // The terminal rows must be keyed by the same mapping, so a row cannot cite
    // a spelling that resolves elsewhere.
    let pine = &contract.terminals["tradingview_pine"];
    let mut cited = 0usize;
    for (name, entry) in &pine.functions {
        let Some(spelling) = entry.via.as_deref() else {
            continue;
        };
        let Some(resolved) = contract.pine_engine_mapping.get(spelling) else {
            panic!("{name}: cites unknown Pine spelling `{spelling}`");
        };
        assert_eq!(
            resolved, name,
            "{name}: cites `{spelling}`, which the engine maps to `{resolved}`"
        );
        cited += 1;
    }
    assert!(
        cited >= 40,
        "only {cited} Pine rows cite the spelling that substantiated them"
    );
}
