//! Contract test for the four-terminal formula dialect coverage matrix.
//!
//! `tests/contracts/formula_dialect_coverage_v1.json` is generated by
//! `scripts/gen_dialect_coverage.py`. This gate keeps the contract honest in
//! the directions that matter:
//!
//! 1. **Statuses must agree with the runtime.** `exact`/`near`/`approximate`
//!    claim a name runs out of the box, so the engine must register it;
//!    `unsupported` claims it does not, so the engine must not. `host_required`
//!    is the *reason* a name is not out-of-the-box coverage (the host must
//!    inject market/session data) and deliberately makes no registration claim.
//! 2. **`registered` is a machine fact.** It is re-derived from the live
//!    function table, so a row cannot claim a registration that does not exist.
//!    This is the check that caught `REFX` being credited as coverage.
//! 3. **Provenance is substantiated, not asserted.** Every row tagged
//!    `repo:*` must actually contain its reference name in the file the tag
//!    points at. Hand-written traceability is what produced five false
//!    `repo:functions_legacy` tags before this gate existed.
//! 4. **The corpus must live inside the claimed coverage.** Every function a
//!    checked-in corpus formula calls must not be `unsupported`.

mod common;

use serde::Deserialize;
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

const CONTRACT: &str = "tests/contracts/formula_dialect_coverage_v1.json";
const CORPUS_DIR: &str = "tests/formula_corpus";
const CLASSIC_SOURCE: &str = "repo:talib_coverage_matrix";

#[derive(Debug, Deserialize)]
struct Contract {
    schema_version: u32,
    generated_by: String,
    collected: String,
    statuses: Vec<String>,
    runtime_formula_surface: usize,
    /// Tag -> repository-relative path. Declared by the generator so this gate
    /// can substantiate provenance without duplicating the mapping.
    provenance_sources: BTreeMap<String, String>,
    /// Vendor function lists. Not files, so they can only ever explain an
    /// `attributed` row; declaring them keeps the tag vocabulary closed.
    vendor_sources: BTreeMap<String, String>,
    terminals: BTreeMap<String, Terminal>,
    unverified_candidates: BTreeMap<String, Vec<String>>,
}

#[derive(Debug, Deserialize)]
struct Terminal {
    id: String,
    label: String,
    reference: String,
    collected: String,
    reference_size: usize,
    verified_size: usize,
    attributed_size: usize,
    functions: BTreeMap<String, Entry>,
    coverage: BTreeMap<String, usize>,
    coverage_pct: f64,
    verified_coverage_pct: f64,
    registered: usize,
    host_dependent_registered: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct Entry {
    status: String,
    /// Machine fact: is the name in the engine's function table?
    registered: bool,
    source: String,
    /// `verified` (found in a named in-repo file) or `attributed` (a vendor
    /// function list this repository cannot read).
    provenance: String,
    /// The token that substantiated the row, when it differs from the
    /// canonical name (a Pine `ta.*` spelling, say).
    via: Option<String>,
}

#[derive(Debug, Deserialize)]
struct CorpusCase {
    id: String,
    platform: String,
    source_formula: String,
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..")
}

fn load_contract() -> Contract {
    let path = workspace_root().join(CONTRACT);
    let raw = fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
    serde_json::from_str(&raw).expect("parse dialect coverage contract")
}

/// Platform tag in `tests/formula_corpus/*.json` -> contract terminal key.
fn terminal_for_platform(platform: &str) -> &'static str {
    match platform.to_ascii_lowercase().as_str() {
        "tdx" | "cross" => "tongdaxin",
        "ths" => "tonghuashun",
        "dzh" => "dazhihui",
        "pine" | "tradingview" => "tradingview_pine",
        other => panic!("corpus platform {other} has no contract terminal"),
    }
}

/// Function names a formula source calls: `NAME(` at an identifier boundary.
fn called_functions(source: &str) -> BTreeSet<String> {
    let bytes = source.as_bytes();
    let mut names = BTreeSet::new();
    for (index, byte) in bytes.iter().enumerate() {
        if *byte != b'(' {
            continue;
        }
        let mut start = index;
        while start > 0 {
            let previous = bytes[start - 1];
            if previous.is_ascii_alphanumeric() || previous == b'_' {
                start -= 1;
            } else {
                break;
            }
        }
        if start == index {
            continue;
        }
        let candidate = &source[start..index];
        if candidate
            .chars()
            .next()
            .is_some_and(|first| first.is_ascii_alphabetic() || first == '_')
        {
            names.insert(candidate.to_ascii_uppercase());
        }
    }
    names
}

fn corpus_cases() -> Vec<CorpusCase> {
    let root = workspace_root().join(CORPUS_DIR);
    let mut paths: Vec<PathBuf> = fs::read_dir(&root)
        .unwrap_or_else(|error| panic!("read {}: {error}", root.display()))
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().is_some_and(|ext| ext == "json"))
        .collect();
    paths.sort();
    paths
        .iter()
        .map(|path| {
            let raw = fs::read_to_string(path).expect("read corpus case");
            serde_json::from_str(&raw)
                .unwrap_or_else(|error| panic!("parse {}: {error}", path.display()))
        })
        .collect()
}

/// Whole-token containment: `COG` must not be substantiated by `COGS`.
fn contains_token(text: &str, token: &str) -> bool {
    let bytes = text.as_bytes();
    let needle = token.as_bytes();
    if needle.is_empty() || needle.len() > bytes.len() {
        return false;
    }
    let is_word = |b: u8| b.is_ascii_alphanumeric() || b == b'_';
    for start in 0..=(bytes.len() - needle.len()) {
        if &bytes[start..start + needle.len()] != needle {
            continue;
        }
        let before_ok = start == 0 || !is_word(bytes[start - 1]);
        let end = start + needle.len();
        let after_ok = end == bytes.len() || !is_word(bytes[end]);
        if before_ok && after_ok {
            return true;
        }
    }
    false
}

#[test]
fn contract_is_self_consistent_and_covers_four_terminals() {
    let contract = load_contract();
    assert_eq!(contract.schema_version, 1);
    assert_eq!(contract.generated_by, "scripts/gen_dialect_coverage.py");
    assert!(!contract.collected.is_empty());
    assert!(
        contract.runtime_formula_surface > 0,
        "contract must record the runtime formula surface it was built against"
    );

    let expected: BTreeSet<&str> = ["tongdaxin", "tonghuashun", "dazhihui", "tradingview_pine"]
        .into_iter()
        .collect();
    let actual: BTreeSet<&str> = contract.terminals.keys().map(String::as_str).collect();
    assert_eq!(actual, expected, "terminal set changed");

    let statuses: BTreeSet<&str> = contract.statuses.iter().map(String::as_str).collect();
    assert_eq!(
        statuses,
        BTreeSet::from([
            "exact",
            "near",
            "approximate",
            "host_required",
            "unsupported"
        ]),
        "the five-state vocabulary is part of the contract"
    );

    for (key, terminal) in &contract.terminals {
        assert!(
            terminal.reference_size >= 200,
            "{key}: reference list is only {} entries",
            terminal.reference_size
        );
        assert_eq!(
            terminal.functions.len(),
            terminal.reference_size,
            "{key}: reference_size disagrees with the function table"
        );
        assert_eq!(
            terminal.verified_size + terminal.attributed_size,
            terminal.reference_size,
            "{key}: verified + attributed must account for every row"
        );
        assert_eq!(
            terminal.collected, contract.collected,
            "{key}: terminals were collected on different dates"
        );
        assert!(
            !terminal.reference.is_empty() && !terminal.label.is_empty(),
            "{key}: every terminal must name its reference and label"
        );

        // Recompute every aggregate from the rows instead of trusting it.
        let mut recomputed: BTreeMap<&str, usize> =
            contract.statuses.iter().map(|s| (s.as_str(), 0)).collect();
        let mut registered = 0usize;
        let mut verified = 0usize;
        let mut host_dependent_registered = Vec::new();
        let mut out_of_the_box = 0usize;
        let mut out_of_the_box_verified = 0usize;
        for (name, entry) in &terminal.functions {
            assert!(
                contract.statuses.contains(&entry.status),
                "{key}/{name}: unknown status {}",
                entry.status
            );
            let declared = if entry.source.starts_with("vendor:") {
                contract.vendor_sources.contains_key(&entry.source)
            } else {
                contract.provenance_sources.contains_key(&entry.source)
            };
            assert!(
                declared,
                "{key}/{name}: source `{}` is not a declared provenance tag",
                entry.source
            );
            assert!(
                matches!(entry.provenance.as_str(), "verified" | "attributed"),
                "{key}/{name}: unknown provenance {}",
                entry.provenance
            );
            // A `repo:` tag is only ever allowed on a substantiated row; if we
            // cannot read the file, the row must fall back to `vendor:`.
            match entry.provenance.as_str() {
                "attributed" => assert!(
                    entry.source.starts_with("vendor:"),
                    "{key}/{name}: `{}` is attributed but is not a vendor source",
                    entry.source
                ),
                "verified" => assert!(
                    !entry.source.starts_with("vendor:"),
                    "{key}/{name}: `{}` claims verification by a vendor list",
                    entry.source
                ),
                _ => {}
            }
            *recomputed.entry(entry.status.as_str()).or_default() += 1;
            if entry.registered {
                registered += 1;
            }
            if entry.provenance == "verified" {
                verified += 1;
            }
            if entry.status == "host_required" && entry.registered {
                host_dependent_registered.push(name.clone());
            }
            let runs = matches!(entry.status.as_str(), "exact" | "near" | "approximate");
            if runs {
                out_of_the_box += 1;
                if entry.provenance == "verified" {
                    out_of_the_box_verified += 1;
                }
            }
        }
        for status in &contract.statuses {
            assert_eq!(
                terminal.coverage.get(status).copied().unwrap_or(0),
                recomputed[status.as_str()],
                "{key}: coverage[{status}] does not match the rows"
            );
        }
        assert_eq!(
            terminal.registered, registered,
            "{key}: registered count does not match the rows"
        );
        assert_eq!(
            terminal.verified_size, verified,
            "{key}: verified_size does not match the rows"
        );
        assert_eq!(
            terminal.host_dependent_registered, host_dependent_registered,
            "{key}: host_dependent_registered does not match the rows"
        );
        let pct = |numerator: usize, denominator: usize| -> f64 {
            if denominator == 0 {
                0.0
            } else {
                (1000.0 * numerator as f64 / denominator as f64).round() / 10.0
            }
        };
        assert!(
            (terminal.coverage_pct - pct(out_of_the_box, terminal.reference_size)).abs() < 0.05,
            "{key}: coverage_pct {} does not match the rows",
            terminal.coverage_pct
        );
        assert!(
            (terminal.verified_coverage_pct - pct(out_of_the_box_verified, terminal.verified_size))
                .abs()
                < 0.05,
            "{key}: verified_coverage_pct {} does not match the rows",
            terminal.verified_coverage_pct
        );
        assert!(
            terminal.registered >= out_of_the_box,
            "{key}: {registered} registered rows cannot be fewer than the \
             {out_of_the_box} out-of-the-box rows"
        );
    }

    // A dropped name must not also appear as a row: the contract reports the
    // unsourced surface separately instead of laundering it into a percentage.
    for (key, names) in &contract.unverified_candidates {
        let terminal = contract
            .terminals
            .get(key)
            .unwrap_or_else(|| panic!("unverified_candidates names an unknown terminal {key}"));
        for name in names {
            assert!(
                !terminal.functions.contains_key(name),
                "{key}/{name}: reported as unverified but also counted as a row"
            );
        }
    }
}

/// Every `repo:*` row must actually be substantiated by the file it cites.
///
/// This is the assertion that makes the contract's central promise -- "every
/// reference name is traceable to a named source" -- mechanically true rather
/// than a claim the generator makes about itself.
#[test]
fn every_verified_provenance_tag_is_substantiated() {
    let contract = load_contract();
    let mut checked = 0usize;
    let mut problems = Vec::new();

    for (key, terminal) in &contract.terminals {
        for (name, entry) in &terminal.functions {
            if entry.provenance != "verified" {
                continue;
            }
            let Some(relative) = contract.provenance_sources.get(&entry.source) else {
                problems.push(format!("{key}/{name}: undeclared source {}", entry.source));
                continue;
            };
            let path = workspace_root().join(relative);
            let text = fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
            // A Pine row is substantiated by its `ta.*` spelling rather than by
            // the canonical name it maps to.
            let token = entry.via.as_deref().unwrap_or(name.as_str());
            if !contains_token(&text, token) {
                problems.push(format!(
                    "{key}/{name}: `{token}` not found in {relative}, so `{}` is unsubstantiated",
                    entry.source
                ));
            }
            checked += 1;
        }
    }

    assert!(
        problems.is_empty(),
        "provenance tags are not substantiated:\n{}",
        problems.join("\n")
    );
    assert!(
        checked >= 800,
        "only {checked} rows carry substantiated provenance; the contract has \
         regressed to hand-written traceability"
    );
    assert!(
        !contract.provenance_sources.is_empty()
            && contract.provenance_sources.contains_key(CLASSIC_SOURCE),
        "the classic TA core must be substantiated by the coverage matrix"
    );
}

#[test]
fn contract_statuses_agree_with_the_runtime_formula_table() {
    let contract = load_contract();
    let runtime = finkit::formula::functions::get_builtin_functions();

    let mut problems = Vec::new();
    for (key, terminal) in &contract.terminals {
        for (name, entry) in &terminal.functions {
            let callable = runtime.contains_key(name.as_str());

            // `registered` is a machine fact and must match the live engine
            // exactly. This is the check that catches a row claiming a
            // registration that does not exist.
            if entry.registered != callable {
                problems.push(format!(
                    "{key}/{name}: `registered` says {} but the engine says {callable}",
                    entry.registered
                ));
            }

            match entry.status.as_str() {
                "exact" | "near" | "approximate" => {
                    if !callable {
                        problems.push(format!(
                            "{key}/{name}: claimed `{}` (out of the box) but the \
                             engine registers no implementation",
                            entry.status
                        ));
                    }
                }
                "unsupported" => {
                    if callable {
                        problems.push(format!(
                            "{key}/{name}: claimed `unsupported` but the runtime \
                             registers it"
                        ));
                    }
                }
                // The reason for non-coverage; makes no registration claim.
                "host_required" => {}
                other => problems.push(format!("{key}/{name}: unknown status {other}")),
            }
        }
    }
    assert!(
        problems.is_empty(),
        "dialect contract disagrees with the runtime:\n{}",
        problems.join("\n")
    );
}

#[test]
fn corpus_formulas_stay_inside_the_claimed_coverage() {
    let contract = load_contract();
    let mut checked = 0usize;
    let mut problems = Vec::new();

    for case in corpus_cases() {
        let key = terminal_for_platform(&case.platform);
        let terminal = contract
            .terminals
            .get(key)
            .unwrap_or_else(|| panic!("{}: unknown terminal key {key}", case.id));
        for name in called_functions(&case.source_formula) {
            let Some(entry) = terminal.functions.get(&name) else {
                // Not part of this terminal's reference list: the contract makes
                // no claim about it, so the corpus is free to use it.
                continue;
            };
            checked += 1;
            if entry.status == "unsupported" {
                problems.push(format!(
                    "{} ({}): calls {name}, which the contract marks `unsupported`",
                    case.id, terminal.id
                ));
            }
        }
    }

    assert!(
        problems.is_empty(),
        "corpus uses functions outside the claimed coverage:\n{}",
        problems.join("\n")
    );
    assert!(
        checked >= 20,
        "corpus/contract overlap is only {checked} function references; \
         the corpus and the contract have drifted apart"
    );
}
