//! Phase 8 黄金测试框架示例
//!
//! 演示如何用 `core/tests/common/` 公共模块编写黄金测试：
//! 1. `mod common;` 引用共享 helper
//! 2. `load_golden` 加载 TA-Lib / 同花顺导出的参考 CSV
//! 3. 本库指标输出与参考值在 `1e-9` 容差下逐值对比
//!
//! 实际接入 150+ 指标的工作留到 Phase 8 后续增量任务与 Phase 3 完成。
//!
//! 本示例采用 round-trip 工作流（库输出 → 临时黄金 CSV → `load_golden` 读回 →
//! `assert_approx_eq_slice`），避免与 `core/tests/golden_tests.rs` 维护的
//! workspace 级黄金文件产生格式耦合（那些文件是 `index,value` 两列格式，
//! `load_golden` 只取第一列）。

use alpha_ta_core::math::moving_avg::sma;
use std::fs::File;
use std::io::Write;

mod common;
use common::golden_loader::{assert_approx_eq_slice, load_golden, DEFAULT_TOLERANCE};

/// 写一个临时单列 CSV（含 `# Generated by ...` 注释头与若干空行），
/// 返回文件路径。调用方负责清理。
fn write_temp_golden(values: &[f64]) -> std::path::PathBuf {
    let dir = std::env::temp_dir();
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let path = dir.join(format!(
        "alpha_ta_golden_example_{}_{}.csv",
        std::process::id(),
        nanos
    ));
    let mut f = File::create(&path).expect("create temp golden");
    writeln!(f, "# Generated by alpha_ta-core example").unwrap();
    writeln!(f).unwrap();
    for v in values {
        writeln!(f, "{}", v).unwrap();
    }
    path
}

#[test]
fn test_sma_10_roundtrip_via_golden_helper() {
    // 50 根合成 close：40000 附近正弦波动，period=10。
    let close: Vec<f64> = (0..50)
        .map(|i| {
            let i_f = i as f64;
            40000.0 + i_f * 50.0 + 100.0 * (i_f * 0.5).sin()
        })
        .collect();
    let result = sma(&close, 10).unwrap();
    assert_eq!(result.len(), 50);

    // round-trip：把库输出写到临时黄金 CSV → 读回 → 逐值对比。
    let actual: Vec<f64> = result.iter().copied().collect();
    let golden_path = write_temp_golden(&actual);
    let loaded = load_golden(&golden_path);
    assert_eq!(loaded.len(), actual.len());
    assert_approx_eq_slice(&actual, &loaded, DEFAULT_TOLERANCE);

    // 二次对比：再计算一次 SMA，验证 helper 解析的数值仍能与本库输出对齐。
    let result2 = sma(&close, 10).unwrap();
    let actual2: Vec<f64> = result2.iter().copied().collect();
    assert_approx_eq_slice(&actual, &actual2, 0.0);

    let _ = std::fs::remove_file(&golden_path);
}

#[test]
fn test_sma_warmup_is_nan() {
    // 前 period-1 项为 NaN 的契约：未来黄金测试在解析阶段也会跳过这些行。
    let close: Vec<f64> = (0..20).map(|i| i as f64).collect();
    let result = sma(&close, 5).unwrap();
    for (i, v) in result.iter().enumerate() {
        if i < 4 {
            assert!(v.is_nan(), "warmup idx {} should be NaN, got {}", i, v);
        } else {
            assert!(!v.is_nan(), "post-warmup idx {} should be finite", i);
        }
    }
}

#[test]
fn test_load_golden_helper_handles_header_and_blank_lines() {
    // 写一个含头 + 空行 + 多列的临时 CSV，验证 helper 解析行为。
    let path = std::env::temp_dir().join(format!(
        "alpha_ta_golden_header_{}_{}.csv",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0)
    ));
    {
        let mut f = File::create(&path).expect("create tmp");
        writeln!(f, "# Generated by TA-Lib 0.6.x").unwrap();
        writeln!(f).unwrap();
        writeln!(f, "1.0,extra1,extra2").unwrap();
        writeln!(f, "2.0").unwrap();
        writeln!(f, "# trailing comment").unwrap();
        writeln!(f, "3.0,extra").unwrap();
    }
    let values = load_golden(&path);
    assert_eq!(values, vec![1.0, 2.0, 3.0]);
    let _ = std::fs::remove_file(&path);
}
