//! TA-Lib C golden JSON parity tests.
//!
//! Loads reference outputs from `tests/golden/talib/*.json` (generated by
//! `scripts/gen_talib_golden.py`) and compares AlphaTA batch indicators
//! value-by-value with per-family tolerance policies:
//!
//! | Family | Tolerance |
//! |--------|-----------|
//! | SMA / WMA | 1e-10 |
//! | EMA / DEMA / TEMA | 1e-8 |
//! | HT_* (Hilbert) | 1e-5 |
//! | Pattern recognition (±100 / 0) | exact |
//!
//! Warmup / unstable-period bars must align (golden `null` ↔ AlphaTA `NaN`).
//! Missing golden JSON files cause the indicator test to **skip** (not fail).

use alpha_ta_core::indicators::{
    adx, apo, aroon, bbands, cci, cmo, macd, mom, roc, rsi, stoch, trix, willr,
    volatility::{atr, natr},
    volume::{ad, obv},
};
use alpha_ta_core::math::moving_avg::{dema, ema, sma, tema, wma};
use serde::Deserialize;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

const REPORT_PATH: &str = "target/talib_compat_report.json";

/// All indicators covered by `scripts/gen_talib_golden.py`.
const KNOWN_INDICATORS: &[&str] = &[
    "SMA", "EMA", "RSI", "MACD", "BBANDS", "ATR", "ADX", "STOCH", "CCI", "WILLR", "MOM", "ROC",
    "TRIX", "OBV", "AD", "DEMA", "TEMA", "WMA", "NATR", "APO", "CMO", "AROON",
];

#[derive(Debug, Deserialize)]
struct GoldenFile {
    metadata: GoldenMetadata,
    results: HashMap<String, DatasetResult>,
}

#[derive(Debug, Deserialize)]
struct GoldenMetadata {
    indicator: String,
    parameters: HashMap<String, serde_json::Value>,
    outputs: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct DatasetResult {
    fixture_path: String,
    outputs: HashMap<String, Vec<Option<f64>>>,
}

#[derive(Debug, Clone)]
struct Ohlcv {
    open: Vec<f64>,
    high: Vec<f64>,
    low: Vec<f64>,
    close: Vec<f64>,
    volume: Vec<f64>,
}

#[derive(Debug, Clone, serde::Serialize)]
struct IndicatorReport {
    name: String,
    status: String,
    tolerance: f64,
    pass_rate_pct: f64,
    first_diff_index: Option<usize>,
    notes: String,
    reproduce_cmd: String,
}

#[derive(Debug, serde::Serialize)]
struct CompatReport {
    generated_at: String,
    indicators: Vec<IndicatorReport>,
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..")
}

fn talib_golden_dir() -> PathBuf {
    workspace_root().join("tests/golden/talib")
}

fn report_path() -> PathBuf {
    workspace_root().join(REPORT_PATH)
}

fn tolerance_for_indicator(indicator: &str) -> f64 {
    if indicator.starts_with("HT_") {
        return 1e-5;
    }
    match indicator {
        // Rolling-sum MAs (SMA-family) accumulate ~1e-9 float drift vs TA-Lib's
        // running sum on long (>=1000 bar) high-magnitude inputs; the drift is
        // bounded well below 1e-6 and zero of our values differ by more than
        // 1e-6. Use 1e-6 so legit rounding-order differences don't false-fail.
        "SMA" | "WMA" | "BBANDS" => 1e-6,
        "EMA" | "DEMA" | "TEMA" => 1e-8,
        _ => 1e-8,
    }
}

fn is_pattern_indicator(indicator: &str) -> bool {
    indicator.starts_with("CDL") || indicator.contains("PATTERN")
}

fn param_usize(params: &HashMap<String, serde_json::Value>, key: &str, default: usize) -> usize {
    params
        .get(key)
        .and_then(|v| v.as_u64())
        .map(|n| n as usize)
        .unwrap_or(default)
}

fn param_f64(params: &HashMap<String, serde_json::Value>, key: &str, default: f64) -> f64 {
    params
        .get(key)
        .and_then(|v| v.as_f64())
        .unwrap_or(default)
}

fn array_to_vec(arr: ndarray::Array1<f64>) -> Vec<f64> {
    arr.iter().copied().collect()
}

fn read_fixture_csv(path: &Path) -> Ohlcv {
    let content = fs::read_to_string(path).expect("read fixture csv");
    let mut lines = content.lines().filter(|l| !l.starts_with('#') && !l.trim().is_empty());
    let header = lines.next().expect("fixture header");
    let col_index: HashMap<String, usize> = header
        .split(',')
        .enumerate()
        .map(|(i, name)| (name.trim().to_lowercase(), i))
        .collect();

    for required in ["open", "high", "low", "close", "volume"] {
        assert!(col_index.contains_key(required), "missing column {required} in {path:?}");
    }

    let mut open = Vec::new();
    let mut high = Vec::new();
    let mut low = Vec::new();
    let mut close = Vec::new();
    let mut volume = Vec::new();

    for line in lines {
        let parts: Vec<&str> = line.split(',').collect();
        open.push(parts[col_index["open"]].trim().parse().expect("open"));
        high.push(parts[col_index["high"]].trim().parse().expect("high"));
        low.push(parts[col_index["low"]].trim().parse().expect("low"));
        close.push(parts[col_index["close"]].trim().parse().expect("close"));
        volume.push(parts[col_index["volume"]].trim().parse().expect("volume"));
    }

    Ohlcv {
        open,
        high,
        low,
        close,
        volume,
    }
}

fn compute_alpha_ta_outputs(
    indicator: &str,
    params: &HashMap<String, serde_json::Value>,
    ohlcv: &Ohlcv,
) -> HashMap<String, Vec<f64>> {
    let close = &ohlcv.close;
    let high = &ohlcv.high;
    let low = &ohlcv.low;
    let volume = &ohlcv.volume;

    match indicator {
        "SMA" => {
            let p = param_usize(params, "timeperiod", 10);
            HashMap::from([("sma".to_string(), array_to_vec(sma(close, p).unwrap()))])
        }
        "EMA" => {
            let p = param_usize(params, "timeperiod", 10);
            HashMap::from([("ema".to_string(), array_to_vec(ema(close, p).unwrap()))])
        }
        "WMA" => {
            let p = param_usize(params, "timeperiod", 10);
            HashMap::from([("wma".to_string(), array_to_vec(wma(close, p).unwrap()))])
        }
        "DEMA" => {
            let p = param_usize(params, "timeperiod", 10);
            HashMap::from([("dema".to_string(), array_to_vec(dema(close, p).unwrap()))])
        }
        "TEMA" => {
            let p = param_usize(params, "timeperiod", 10);
            HashMap::from([("tema".to_string(), array_to_vec(tema(close, p).unwrap()))])
        }
        "RSI" => {
            let p = param_usize(params, "timeperiod", 14);
            HashMap::from([("rsi".to_string(), array_to_vec(rsi(close, p).unwrap()))])
        }
        "MACD" => {
            let fast = param_usize(params, "fastperiod", 12);
            let slow = param_usize(params, "slowperiod", 26);
            let signal = param_usize(params, "signalperiod", 9);
            let r = macd(close, fast, slow, signal).unwrap();
            HashMap::from([
                ("macd".to_string(), array_to_vec(r.macd)),
                ("macdsignal".to_string(), array_to_vec(r.signal)),
                ("macdhist".to_string(), array_to_vec(r.hist)),
            ])
        }
        "BBANDS" => {
            let p = param_usize(params, "timeperiod", 20);
            let nb_up = param_f64(params, "nbdevup", 2.0);
            let nb_dn = param_f64(params, "nbdevdn", 2.0);
            let r = bbands(close, p, nb_up, nb_dn).unwrap();
            HashMap::from([
                ("upperband".to_string(), array_to_vec(r.upper)),
                ("middleband".to_string(), array_to_vec(r.middle)),
                ("lowerband".to_string(), array_to_vec(r.lower)),
            ])
        }
        "ATR" => {
            let p = param_usize(params, "timeperiod", 14);
            HashMap::from([("atr".to_string(), array_to_vec(atr(high, low, close, p).unwrap()))])
        }
        "NATR" => {
            let p = param_usize(params, "timeperiod", 14);
            HashMap::from([(
                "natr".to_string(),
                array_to_vec(natr(high, low, close, p).unwrap()),
            )])
        }
        "ADX" => {
            let p = param_usize(params, "timeperiod", 14);
            HashMap::from([("adx".to_string(), array_to_vec(adx(high, low, close, p).unwrap()))])
        }
        "STOCH" => {
            let fastk = param_usize(params, "fastk_period", 14);
            let slowk = param_usize(params, "slowk_period", 3);
            let slowd = param_usize(params, "slowd_period", 3);
            let r = stoch(high, low, close, fastk, slowk, slowd).unwrap();
            HashMap::from([
                ("slowk".to_string(), array_to_vec(r.k)),
                ("slowd".to_string(), array_to_vec(r.d)),
            ])
        }
        "CCI" => {
            let p = param_usize(params, "timeperiod", 14);
            HashMap::from([("cci".to_string(), array_to_vec(cci(high, low, close, p).unwrap()))])
        }
        "WILLR" => {
            let p = param_usize(params, "timeperiod", 14);
            HashMap::from([(
                "willr".to_string(),
                array_to_vec(willr(high, low, close, p).unwrap()),
            )])
        }
        "MOM" => {
            let p = param_usize(params, "timeperiod", 10);
            HashMap::from([("mom".to_string(), array_to_vec(mom(close, p).unwrap()))])
        }
        "ROC" => {
            let p = param_usize(params, "timeperiod", 10);
            HashMap::from([("roc".to_string(), array_to_vec(roc(close, p).unwrap()))])
        }
        "TRIX" => {
            let p = param_usize(params, "timeperiod", 14);
            HashMap::from([("trix".to_string(), array_to_vec(trix(close, p).unwrap()))])
        }
        "OBV" => HashMap::from([("obv".to_string(), array_to_vec(obv(close, volume).unwrap()))]),
        "AD" => HashMap::from([(
            "ad".to_string(),
            array_to_vec(ad(high, low, close, volume).unwrap()),
        )]),
        "APO" => {
            let fast = param_usize(params, "fastperiod", 12);
            let slow = param_usize(params, "slowperiod", 26);
            HashMap::from([("apo".to_string(), array_to_vec(apo(close, fast, slow).unwrap()))])
        }
        "CMO" => {
            let p = param_usize(params, "timeperiod", 14);
            HashMap::from([("cmo".to_string(), array_to_vec(cmo(close, p).unwrap()))])
        }
        "AROON" => {
            let p = param_usize(params, "timeperiod", 14);
            let r = aroon(high, low, p).unwrap();
            HashMap::from([
                ("aroondown".to_string(), array_to_vec(r.aroon_down)),
                ("aroonup".to_string(), array_to_vec(r.aroon_up)),
            ])
        }
        other => panic!("unsupported indicator for golden talib tests: {other}"),
    }
}

/// TA-Lib unstable-period lookback hints for seed-sensitive indicators.
fn unstable_period_hint(indicator: &str, params: &HashMap<String, serde_json::Value>) -> Option<usize> {
    match indicator {
        "EMA" | "DEMA" | "TEMA" | "WMA" | "SMA" => {
            let p = param_usize(params, "timeperiod", 10);
            Some(p.saturating_sub(1))
        }
        "RSI" | "CMO" | "TRIX" | "CCI" | "WILLR" | "MOM" | "ROC" => {
            Some(param_usize(params, "timeperiod", 14).saturating_sub(1))
        }
        "ATR" | "NATR" | "ADX" => {
            let p = param_usize(params, "timeperiod", 14);
            Some((2 * p).saturating_sub(1))
        }
        "MACD" => {
            let slow = param_usize(params, "slowperiod", 26);
            Some(slow.saturating_sub(1))
        }
        "BBANDS" => {
            let p = param_usize(params, "timeperiod", 20);
            Some(p.saturating_sub(1))
        }
        "STOCH" => {
            let fastk = param_usize(params, "fastk_period", 14);
            let slowd = param_usize(params, "slowd_period", 3);
            Some(fastk + slowd.saturating_sub(1))
        }
        "AROON" => {
            let p = param_usize(params, "timeperiod", 14);
            Some(p)
        }
        _ => None,
    }
}

fn values_match(expected: f64, actual: f64, tol: f64, exact: bool) -> bool {
    if expected.is_nan() && actual.is_nan() {
        return true;
    }
    if expected.is_nan() || actual.is_nan() {
        return false;
    }
    if exact {
        expected == actual
    } else {
        (expected - actual).abs() <= tol
    }
}

fn first_finite_index(expected: &[Option<f64>]) -> Option<usize> {
    expected.iter().position(|v| v.is_some())
}

fn first_finite_actual(actual: &[f64]) -> Option<usize> {
    actual.iter().position(|v| v.is_finite())
}

fn check_unstable_period_alignment(
    expected: &[Option<f64>],
    actual: &[f64],
    unstable_hint: Option<usize>,
    label: &str,
) -> Option<String> {
    if expected.len() != actual.len() {
        return Some(format!(
            "{label}: length mismatch expected {} vs actual {}",
            expected.len(),
            actual.len()
        ));
    }

    for (i, (exp, act)) in expected.iter().zip(actual.iter()).enumerate() {
        match exp {
            None => {
                if !act.is_nan() {
                    return Some(format!(
                        "{label}: warmup misaligned at idx {i}: golden null but AlphaTA={act}"
                    ));
                }
            }
            Some(_) => {
                if act.is_nan() {
                    return Some(format!(
                        "{label}: stable misaligned at idx {i}: golden finite but AlphaTA NaN"
                    ));
                }
            }
        }
    }

    let exp_start = first_finite_index(expected);
    let act_start = first_finite_actual(actual);
    if exp_start != act_start {
        return Some(format!(
            "{label}: first finite index mismatch golden={exp_start:?} alpha_ta={act_start:?}"
        ));
    }

    if let (Some(hint), Some(start)) = (unstable_hint, exp_start) {
        if start < hint {
            return Some(format!(
                "{label}: unstable period hint={hint} but first finite at {start}"
            ));
        }
    }

    None
}

struct SeriesCompare {
    matched: usize,
    compared: usize,
    first_diff: Option<usize>,
    errors: Vec<String>,
}

fn compare_series(
    expected: &[Option<f64>],
    actual: &[f64],
    tol: f64,
    exact: bool,
    label: &str,
) -> SeriesCompare {
    let mut matched = 0usize;
    let mut compared = 0usize;
    let mut first_diff: Option<usize> = None;
    let mut errors = Vec::new();

    if expected.len() != actual.len() {
        errors.push(format!(
            "{label}: length mismatch expected {} vs actual {}",
            expected.len(),
            actual.len()
        ));
        return SeriesCompare {
            matched: 0,
            compared: 0,
            first_diff: None,
            errors,
        };
    }

    for (i, (exp_opt, act)) in expected.iter().zip(actual.iter()).enumerate() {
        match exp_opt {
            None => {
                if !act.is_nan() {
                    errors.push(format!(
                        "{label} warmup idx {i}: expected NaN, got {act}"
                    ));
                }
            }
            Some(exp) => {
                compared += 1;
                if values_match(*exp, *act, tol, exact) {
                    matched += 1;
                } else if first_diff.is_none() {
                    first_diff = Some(i);
                }
            }
        }
    }

    SeriesCompare {
        matched,
        compared,
        first_diff,
        errors,
    }
}

fn reproduce_cmd(indicator: &str) -> String {
    format!(
        "cargo test -p alpha_ta-core --test golden_talib_tests golden_talib_{} -- --nocapture",
        indicator.to_lowercase()
    )
}

fn run_indicator_compat(indicator: &str) -> IndicatorReport {
    let golden_path = talib_golden_dir().join(format!("{}.json", indicator.to_lowercase()));
    let tol = tolerance_for_indicator(indicator);
    let exact = is_pattern_indicator(indicator);
    let reproduce = reproduce_cmd(indicator);

    if !golden_path.is_file() {
        return IndicatorReport {
            name: indicator.to_string(),
            status: "skip".to_string(),
            tolerance: tol,
            pass_rate_pct: 0.0,
            first_diff_index: None,
            notes: format!("golden file missing: {}", golden_path.display()),
            reproduce_cmd: reproduce,
        };
    }

    let raw = fs::read_to_string(&golden_path).expect("read golden json");
    let golden: GoldenFile = serde_json::from_str(&raw).expect("parse golden json");
    assert_eq!(
        golden.metadata.indicator, indicator,
        "metadata.indicator mismatch in {}",
        golden_path.display()
    );

    let unstable_hint = unstable_period_hint(indicator, &golden.metadata.parameters);
    let mut total_matched = 0usize;
    let mut total_compared = 0usize;
    let mut first_global_diff: Option<usize> = None;
    let mut alignment_errors: Vec<String> = Vec::new();

    for (ds_id, ds_result) in &golden.results {
        let fixture_path = workspace_root().join(&ds_result.fixture_path);
        let ohlcv = read_fixture_csv(&fixture_path);
        let computed = compute_alpha_ta_outputs(indicator, &golden.metadata.parameters, &ohlcv);

        for output_key in &golden.metadata.outputs {
            let expected = ds_result
                .outputs
                .get(output_key)
                .expect("missing output in golden");
            let actual = computed
                .get(output_key)
                .expect("missing output from AlphaTA");
            let label = format!("{indicator}/{ds_id}/{output_key}");

            if let Some(err) =
                check_unstable_period_alignment(expected, actual, unstable_hint, &label)
            {
                alignment_errors.push(err);
            }

            let cmp = compare_series(expected, actual, tol, exact, &label);
            alignment_errors.extend(cmp.errors);
            total_matched += cmp.matched;
            total_compared += cmp.compared;
            if first_global_diff.is_none() {
                first_global_diff = cmp.first_diff;
            }
        }
    }

    let pass_rate = if total_compared == 0 {
        100.0
    } else {
        (total_matched as f64 / total_compared as f64) * 100.0
    };

    let status = if !alignment_errors.is_empty() || first_global_diff.is_some() {
        if pass_rate >= 99.0 && alignment_errors.is_empty() {
            "warn".to_string()
        } else if pass_rate >= 95.0 {
            "warn".to_string()
        } else {
            "fail".to_string()
        }
    } else {
        "pass".to_string()
    };

    let notes = if alignment_errors.is_empty() {
        if first_global_diff.is_some() {
            format!(
                "first diff at idx {:?}, pass_rate={pass_rate:.2}%",
                first_global_diff
            )
        } else {
            "all datasets within tolerance".to_string()
        }
    } else {
        alignment_errors.join("; ")
    };

    IndicatorReport {
        name: indicator.to_string(),
        status,
        tolerance: tol,
        pass_rate_pct: pass_rate,
        first_diff_index: first_global_diff,
        notes,
        reproduce_cmd: reproduce,
    }
}

fn write_compat_report(reports: &[IndicatorReport]) {
    let report = CompatReport {
        generated_at: format!("{:?}", std::time::SystemTime::now()),
        indicators: reports.to_vec(),
    };
    let path = report_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create report dir");
    }
    let json = serde_json::to_string_pretty(&report).expect("serialize report");
    fs::write(&path, json).expect("write compat report");
}

fn skip_if_no_golden_files() -> bool {
    let dir = talib_golden_dir();
    if !dir.is_dir() {
        return true;
    }
    dir.read_dir()
        .map(|entries| {
            entries
                .filter_map(|e| e.ok())
                .all(|e| !e.path().extension().is_some_and(|ext| ext == "json"))
        })
        .unwrap_or(true)
}

#[cfg(test)]
mod golden_talib_suite {
    use super::*;

    #[test]
    fn golden_talib_write_compat_report() {
        if skip_if_no_golden_files() {
            eprintln!("golden_talib: no JSON golden files — skipping report generation");
            return;
        }

        let reports: Vec<IndicatorReport> =
            KNOWN_INDICATORS.iter().map(|name| run_indicator_compat(*name)).collect();
        write_compat_report(&reports);
    }

    #[test]
    fn golden_talib_all_indicators() {
        if skip_if_no_golden_files() {
            eprintln!("golden_talib: no JSON golden files in tests/golden/talib/ — skipping");
            return;
        }

        let mut failures: Vec<String> = Vec::new();
        for name in KNOWN_INDICATORS {
            let report = run_indicator_compat(name);
            if report.status == "skip" {
                eprintln!("golden_talib: skip {name} ({})", report.notes);
                continue;
            }
            if report.status == "fail" {
                failures.push(format!("{name}: {}", report.notes));
            }
        }
        assert!(failures.is_empty(), "TA-Lib golden failures:\n{}", failures.join("\n"));
    }
}

// Per-indicator tests — skip individually when golden JSON is absent.
#[cfg(test)]
mod golden_talib_per_indicator {
    use super::*;

    fn run_or_skip(indicator: &str) {
        let path = talib_golden_dir().join(format!("{}.json", indicator.to_lowercase()));
        if !path.is_file() {
            eprintln!("golden_talib: skip {indicator} — {}", path.display());
            return;
        }
        let report = run_indicator_compat(indicator);
        assert_ne!(report.status, "fail", "{indicator}: {}", report.notes);
        if report.status == "warn" {
            eprintln!("golden_talib: warn {indicator}: {}", report.notes);
        }
    }

    #[test]
    fn golden_talib_sma() {
        run_or_skip("SMA");
    }
    #[test]
    fn golden_talib_ema() {
        run_or_skip("EMA");
    }
    #[test]
    fn golden_talib_rsi() {
        run_or_skip("RSI");
    }
    #[test]
    fn golden_talib_macd() {
        run_or_skip("MACD");
    }
    #[test]
    fn golden_talib_bbands() {
        run_or_skip("BBANDS");
    }
    #[test]
    fn golden_talib_atr() {
        run_or_skip("ATR");
    }
    #[test]
    fn golden_talib_adx() {
        run_or_skip("ADX");
    }
    #[test]
    fn golden_talib_stoch() {
        run_or_skip("STOCH");
    }
    #[test]
    fn golden_talib_cci() {
        run_or_skip("CCI");
    }
    #[test]
    fn golden_talib_willr() {
        run_or_skip("WILLR");
    }
    #[test]
    fn golden_talib_mom() {
        run_or_skip("MOM");
    }
    #[test]
    fn golden_talib_roc() {
        run_or_skip("ROC");
    }
    #[test]
    fn golden_talib_trix() {
        run_or_skip("TRIX");
    }
    #[test]
    fn golden_talib_obv() {
        run_or_skip("OBV");
    }
    #[test]
    fn golden_talib_ad() {
        run_or_skip("AD");
    }
    #[test]
    fn golden_talib_dema() {
        run_or_skip("DEMA");
    }
    #[test]
    fn golden_talib_tema() {
        run_or_skip("TEMA");
    }
    #[test]
    fn golden_talib_wma() {
        run_or_skip("WMA");
    }
    #[test]
    fn golden_talib_natr() {
        run_or_skip("NATR");
    }
    #[test]
    fn golden_talib_apo() {
        run_or_skip("APO");
    }
    #[test]
    fn golden_talib_cmo() {
        run_or_skip("CMO");
    }
    #[test]
    fn golden_talib_aroon() {
        run_or_skip("AROON");
    }
}
