//! TA-Lib profile-only names exposed by the shared dispatcher.
//!
//! The Core registry describes the native/core semantic surface.  The
//! versioned TA-Lib profile is a second, explicit public surface and must not
//! disappear from discovery merely because a function has no Core equivalent.
//! Some names are also present in the Core registry. The complete dispatcher
//! surface is the union of this profile-only list and Core registry names;
//! keeping the profile-only list here makes discovery deterministic across all
//! bindings.

/// Canonical semantic profile identifier for the current TA-Lib core contract.
///
/// Keep this in one module so the dispatcher, operation catalog and bindings
/// cannot silently drift to different version strings.
pub const TALIB_SEMANTIC_PROFILE: &str = "talib_0_8_0";

/// Upstream TA-Lib core version represented by [`TALIB_SEMANTIC_PROFILE`].
pub const TALIB_CORE_VERSION: &str = "0.8.1";

/// TA-Lib 0.8.0 profile-only names exposed by the versioned dispatcher.
pub const TALIB_PROFILE_CATALOG_NAMES: &[&str] = &[
    "AC",
    "ACOS",
    "ADR",
    "ADX",
    "ADXR",
    "AO",
    "APO",
    "AROON",
    "AROONOSC",
    "ASIN",
    "ATAN",
    "AVGPRICE",
    "BOP",
    "CDL2CROWS",
    "CDL3BLACKCROWS",
    "CDL3INSIDE",
    "CDL3LINESTRIKE",
    "CDL3OUTSIDE",
    "CDL3STARSINSOUTH",
    "CDL3WHITESOLDIERS",
    "CDLABANDONEDBABY",
    "CDLADVANCEBLOCK",
    "CDLBELTHOLD",
    "CDLBREAKAWAY",
    "CDLCLOSINGMARUBOZU",
    "CDLCONCEALBABYSWALL",
    "CDLCOUNTERATTACK",
    "CDLDARKCLOUDCOVER",
    "CDLDOJI",
    "CDLDOJISTAR",
    "CDLDRAGONFLYDOJI",
    "CDLENGULFING",
    "CDLEVENINGDOJISTAR",
    "CDLEVENINGSTAR",
    "CDLGAPSIDESIDEWHITE",
    "CDLGRAVESTONEDOJI",
    "CDLHAMMER",
    "CDLHANGINGMAN",
    "CDLHARAMI",
    "CDLHARAMICROSS",
    "CDLHIGHWAVE",
    "CDLHIKKAKE",
    "CDLHIKKAKEMOD",
    "CDLHOMINGPIGEON",
    "CDLIDENTICAL3CROWS",
    "CDLINNECK",
    "CDLINVERTEDHAMMER",
    "CDLKICKING",
    "CDLKICKINGBYLENGTH",
    "CDLLADDERBOTTOM",
    "CDLLONGLEGGEDDOJI",
    "CDLLONGLINE",
    "CDLMARUBOZU",
    "CDLMATCHINGLOW",
    "CDLMATHOLD",
    "CDLMORNINGDOJISTAR",
    "CDLMORNINGSTAR",
    "CDLONNECK",
    "CDLPIERCING",
    "CDLRICKSHAWMAN",
    "CDLRISEFALL3METHODS",
    "CDLSEPARATINGLINES",
    "CDLSHOOTINGSTAR",
    "CDLSHORTLINE",
    "CDLSPINNINGTOP",
    "CDLSTALLEDPATTERN",
    "CDLSTICKSANDWICH",
    "CDLTAKURI",
    "CDLTASUKIGAP",
    "CDLTHRUSTING",
    "CDLTRISTAR",
    "CDLUNIQUE3RIVER",
    "CDLUPSIDEGAP2CROWS",
    "CDLXSIDEGAP3METHODS",
    "CEIL",
    "CMF",
    "CMOU",
    "COPPOCK",
    "COS",
    "COSH",
    "CUMSUM",
    "CVI",
    "DPO",
    "DX",
    "EFI",
    "ER",
    "ERI",
    "EXP",
    "FLOOR",
    "FOSC",
    "FRACTAL",
    "HA",
    "HMA",
    "KC",
    "KDJ",
    "LN",
    "LOG10",
    "MARKETFI",
    "MASSI",
    "MEDPRICE",
    "MIDPOINT",
    "MIDPRICE",
    "MINUS_DI",
    "NVI",
    "PERCENTILE",
    "PERCENTRANK",
    "PLUS_DI",
    "PVI",
    "PVO",
    "PVT",
    "QSTICK",
    "RMA",
    "ROCP",
    "ROCR",
    "ROCR100",
    "RVI",
    "RVOL",
    "SAR",
    "SIN",
    "SINH",
    "SMI",
    "SQRT",
    "STOCH",
    "STOCHF",
    "STOCHRSI",
    "TAN",
    "TANH",
    "TRANGE",
    "TRIX",
    "TSI",
    "TYPPRICE",
    "VHF",
    "VORTEX",
    "VWMA",
    "WAD",
    "WCLPRICE",
    "WILLR",
    "ZLEMA",
];

#[inline]
pub fn is_profile_catalog_name(name: &str) -> bool {
    TALIB_PROFILE_CATALOG_NAMES.contains(&name)
}
