//! TA-Lib profile names that are executable by the shared dispatcher.
//!
//! The Core registry describes the native/core semantic surface.  The
//! versioned TA-Lib profile is a second, explicit public surface and must not
//! disappear from discovery merely because a function has no Core equivalent.
//! Some names are also present in the Core registry; keeping the complete
//! profile list here makes discovery deterministic across all bindings.

/// TA-Lib 0.7.1 catalog names exposed by the versioned dispatcher.
pub const TALIB_PROFILE_CATALOG_NAMES: &[&str] = &[
    "ACOS",
    "ADX",
    "ADXR",
    "APO",
    "AROON",
    "AROONOSC",
    "ASIN",
    "ATAN",
    "AVGPRICE",
    "BOP",
    "CDL2CROWS",
    "CDL3BLACKCROWS",
    "CDL3INSIDE",
    "CDL3LINESTRIKE",
    "CDL3OUTSIDE",
    "CDL3STARSINSOUTH",
    "CDL3WHITESOLDIERS",
    "CDLABANDONEDBABY",
    "CDLADVANCEBLOCK",
    "CDLBELTHOLD",
    "CDLBREAKAWAY",
    "CDLCLOSINGMARUBOZU",
    "CDLCONCEALBABYSWALL",
    "CDLCOUNTERATTACK",
    "CDLDARKCLOUDCOVER",
    "CDLDOJI",
    "CDLDOJISTAR",
    "CDLDRAGONFLYDOJI",
    "CDLENGULFING",
    "CDLEVENINGDOJISTAR",
    "CDLEVENINGSTAR",
    "CDLGAPSIDESIDEWHITE",
    "CDLGRAVESTONEDOJI",
    "CDLHAMMER",
    "CDLHANGINGMAN",
    "CDLHARAMI",
    "CDLHARAMICROSS",
    "CDLHIGHWAVE",
    "CDLHIKKAKE",
    "CDLHIKKAKEMOD",
    "CDLHOMINGPIGEON",
    "CDLIDENTICAL3CROWS",
    "CDLINNECK",
    "CDLINVERTEDHAMMER",
    "CDLKICKING",
    "CDLKICKINGBYLENGTH",
    "CDLLADDERBOTTOM",
    "CDLLONGLEGGEDDOJI",
    "CDLLONGLINE",
    "CDLMARUBOZU",
    "CDLMATCHINGLOW",
    "CDLMATHOLD",
    "CDLMORNINGDOJISTAR",
    "CDLMORNINGSTAR",
    "CDLONNECK",
    "CDLPIERCING",
    "CDLRICKSHAWMAN",
    "CDLRISEFALL3METHODS",
    "CDLSEPARATINGLINES",
    "CDLSHOOTINGSTAR",
    "CDLSHORTLINE",
    "CDLSPINNINGTOP",
    "CDLSTALLEDPATTERN",
    "CDLSTICKSANDWICH",
    "CDLTAKURI",
    "CDLTASUKIGAP",
    "CDLTHRUSTING",
    "CDLTRISTAR",
    "CDLUNIQUE3RIVER",
    "CDLUPSIDEGAP2CROWS",
    "CDLXSIDEGAP3METHODS",
    "CEIL",
    "COS",
    "COSH",
    "DX",
    "EXP",
    "FLOOR",
    "LN",
    "LOG10",
    "MEDPRICE",
    "MIDPOINT",
    "MIDPRICE",
    "MINUS_DI",
    "PLUS_DI",
    "ROCP",
    "ROCR",
    "ROCR100",
    "SAR",
    "SIN",
    "SINH",
    "SQRT",
    "STOCH",
    "STOCHF",
    "STOCHRSI",
    "TAN",
    "TANH",
    "TRANGE",
    "TRIX",
    "TYPPRICE",
    "WCLPRICE",
    "WILLR",
];

#[inline]
pub fn is_profile_catalog_name(name: &str) -> bool {
    TALIB_PROFILE_CATALOG_NAMES.contains(&name)
}
