//! Fuzz target for the formula engine (T-2).
//!
//! Runs random formula-like strings through the [`FormulaEngine::eval`] and
//! [`FormulaEngine::eval_partial`] entry points. The contract being tested is
//! that **no input should ever panic** the engine — any combination of
//! syntactically-valid formula tokens, function names, and arithmetic operators
//! must produce either a well-formed `Array1<f64>` or a clean `FormulaError`.
//!
//! # Running
//!
//! ```bash
//! cargo +nightly fuzz run formula -- -runs=50000
//! ```
//!
//! The seed corpus is generated by `gen_corpus.sh` (not committed). Crash
//! reports are written to `fuzz/artifacts/formula/`.
//!
//! # Contract assertions
//!
//! - No panics.
//! - Result `Array1` length is always `ctx.data_len`.
//! - Partial-eval always returns a fully-shaped `Array1`.

#![no_main]

use libfuzzer_sys::fuzz_target;
use finkit::formula::engine::FormulaEngine;
use finkit::formula::types::FormulaContext;
use ndarray::Array1;

/// Make a small synthetic OHLCV context of length `n` from the seed byte.
fn make_ctx(n: usize, seed: u8) -> FormulaContext {
    let s = seed as f64;
    let open: Array1<f64> = (0..n).map(|i| 10.0 + s + (i as f64) * 0.01).collect();
    let high: Array1<f64> = (0..n).map(|i| 11.0 + s + (i as f64) * 0.02).collect();
    let low: Array1<f64> = (0..n).map(|i| 9.0 + s + (i as f64) * 0.01).collect();
    let close: Array1<f64> = (0..n).map(|i| 10.0 + s + (i as f64) * 0.015).collect();
    let volume: Array1<f64> = (0..n).map(|i| 1000.0 + s + (i as f64) * 5.0).collect();
    FormulaContext::new(open, high, low, close, volume, None)
}

fuzz_target!(|data: &[u8]| {
    // Treat the raw input as a UTF-8 string. If it isn't valid UTF-8 we
    // simply skip the iteration — the fuzzer generates plenty of valid
    // strings, and the goal here is to test the **parser/evaluator**, not
    // the byte→str conversion.
    if let Ok(src) = std::str::from_utf8(data) {
        // Limit input size to keep the fuzzer iteration fast. The grammar
        // can theoretically handle arbitrary sizes, but for fuzzing we
        // care about whether a 4KB formula crashes the engine.
        if src.is_empty() || src.len() > 4096 {
            return;
        }

        let n = 16_usize; // Small data: fuzz the engine logic, not throughput.
        let mut ctx = make_ctx(n, data.first().copied().unwrap_or(0));
        let mut engine = FormulaEngine::new();

        // The contract is "no panic". Either an `Ok` array of the right
        // length, or an `Err(_)` with no panic.
        if let Ok(arr) = engine.eval(src, &mut ctx) {
            assert_eq!(arr.len(), n, "eval returned wrong length for: {src:?}");
        }

        // eval_partial must always return a fully-shaped Array1.
        let (arr, errors) = engine.eval_partial(src, &mut ctx);
        assert_eq!(
            arr.len(),
            n,
            "eval_partial returned wrong length for: {src:?} errors={errors:?}"
        );
    }
});
