/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MacdResult {
  macd: number
  signal: number
  histogram: number
}
export interface BollResult {
  upper: number
  middle: number
  lower: number
}
export interface StochResult {
  k: number
  d: number
}
export interface AroonResult {
  up: number
  down: number
}
export interface DonchianResult {
  upper: number
  middle: number
  lower: number
}
export interface IchimokuResult {
  tenkan: number
  kijun: number
  senkouA: number
  senkouB: number
  chikou: number
}
export interface SuperTrendResult {
  supertrend: number
  direction: number
}
export interface KeltnerResult {
  upper: number
  middle: number
  lower: number
}
/** Sweep SMA across multiple periods. */
export declare function sweepSma(data: Array<number>, periods: Array<number>): Array<Array<number>>
/** Sweep EMA across multiple periods. */
export declare function sweepEma(data: Array<number>, periods: Array<number>): Array<Array<number>>
/** Sweep RSI across multiple periods. */
export declare function sweepRsi(data: Array<number>, periods: Array<number>): Array<Array<number>>
/** SweepEngine result for JS. */
export interface JsSweepEngineResult {
  indicator: string
  paramCount: number
  results: Array<Array<number>>
}
/**
 * Generic SweepEngine: Cartesian-product parameter scan.
 *
 * @param indicator - One of "sma", "ema", "rsi"
 * @param data - Price series
 * @param ranges - Array of [start, end, step] arrays
 */
export declare function sweepEngineRun(indicator: string, data: Array<number>, ranges: Array<Array<number>>): JsSweepEngineResult
export declare function transformLogReturn(data: Array<number>): Array<number>
export declare function transformZscore(data: Array<number>): Array<number>
export declare function transformRank(data: Array<number>): Array<number>
export declare function transformDiff(data: Array<number>): Array<number>
export declare function transformRollingMean(data: Array<number>, window: number): Array<number>
/**
 * Simple Moving Average (SMA)
 *
 * Calculates the arithmetic mean of prices over a specified period.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods (default: 5)
 * @returns Array of SMA values
 */
export declare function sma(close: Array<number>, timeperiod: number): Array<number>
/**
 * Exponential Moving Average (EMA)
 *
 * Calculates a moving average that gives more weight to recent prices.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods (default: 12)
 * @returns Array of EMA values
 */
export declare function ema(close: Array<number>, timeperiod: number): Array<number>
/**
 * Weighted Moving Average (WMA)
 *
 * Calculates a moving average that assigns more weight to recent data.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods
 * @returns Array of WMA values
 */
export declare function wma(close: Array<number>, timeperiod: number): Array<number>
/**
 * Double Exponential Moving Average (DEMA)
 *
 * Reduces lag by using a combination of two EMAs.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods
 * @returns Array of DEMA values
 */
export declare function dema(close: Array<number>, timeperiod: number): Array<number>
/**
 * Triple Exponential Moving Average (TEMA)
 *
 * Reduces lag even further than DEMA by using three EMAs.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods
 * @returns Array of TEMA values
 */
export declare function tema(close: Array<number>, timeperiod: number): Array<number>
/**
 * Kaufman Adaptive Moving Average (KAMA)
 *
 * An adaptive moving average that adjusts to market noise.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods
 * @returns Array of KAMA values
 */
export declare function kama(close: Array<number>, timeperiod: number): Array<number>
/**
 * MESA Adaptive Moving Average (MAMA)
 *
 * Uses the Hilbert Transform to adapt to market cycles.
 *
 * @param close - Close prices array
 * @param fastlimit - Fast limit (default: 0.5)
 * @param slowlimit - Slow limit (default: 0.05)
 * @returns Object containing mama and fama arrays
 */
export interface MamaResult {
  mama: Array<number>
  fama: Array<number>
}
/** Result of Darvas Box pattern detection. */
export interface DarvasBoxResult {
  boxTop: Array<number>
  boxBottom: Array<number>
  signal: Array<number>
}
/** Result of Renko brick construction. */
export interface RenkoResult {
  bricks: Array<number>
  direction: Array<number>
}
/** Result of Kagi line construction. */
export interface KagiResult {
  kagi: Array<number>
  direction: Array<number>
}
/** Result of Point & Figure chart. */
export interface PnfResult {
  pnf: Array<number>
  columnType: Array<number>
  newColumn: Array<number>
}
/** Result of Three Line Break chart. */
export interface ThreeLineBreakResult {
  line: Array<number>
  direction: Array<number>
}
/** Result of Williams Alligator indicator. */
export interface WilliamsAlligatorResult {
  jaw: Array<number>
  teeth: Array<number>
  lips: Array<number>
}
/** Result of Heikin-Ashi candlestick. */
export interface HeikinAshiResult {
  haOpen: Array<number>
  haHigh: Array<number>
  haLow: Array<number>
  haClose: Array<number>
}
/** Darvas Box breakout pattern. */
export declare function darvasBox(high: Array<number>, low: Array<number>, close: Array<number>, lookback?: number | undefined | null, confirmation?: number | undefined | null): DarvasBoxResult
/** Renko bricks construction. */
export declare function renko(high: Array<number>, low: Array<number>, boxSize: number): RenkoResult
/** Kagi line construction. */
export declare function kagi(close: Array<number>, reversal: number): KagiResult
/** Point & Figure X/O columns. */
export declare function pointAndFigure(high: Array<number>, low: Array<number>, boxSize: number, reversal: number): PnfResult
/** Three Line Break chart. */
export declare function threeLineBreak(close: Array<number>, lines: number): ThreeLineBreakResult
/** Williams Alligator (5/8/13 SMMA, Bill Williams). */
export declare function williamsAlligator(close: Array<number>): WilliamsAlligatorResult
/** Heikin-Ashi candlestick construction. */
export declare function heikinAshi(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): HeikinAshiResult
export declare function mama(close: Array<number>, fastlimit?: number | undefined | null, slowlimit?: number | undefined | null): MamaResult
/**
 * Triple Exponential Moving Average (T3)
 *
 * A moving average with very little lag and good smoothing.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods
 * @param vfactor - Volume factor (default: 0.7)
 * @returns Array of T3 values
 */
export declare function t3(close: Array<number>, timeperiod: number, vfactor?: number | undefined | null): Array<number>
/**
 * Relative Strength Index (RSI)
 *
 * Measures the magnitude of recent price changes to evaluate overbought/oversold conditions.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods (default: 14)
 * @returns Array of RSI values (0-100)
 */
export declare function rsi(close: Array<number>, timeperiod: number): Array<number>
/** MACD Result structure */
export interface MacdResult {
  macd: Array<number>
  signal: Array<number>
  hist: Array<number>
}
/**
 * Moving Average Convergence Divergence (MACD)
 *
 * Shows the relationship between two EMAs of a security's price.
 *
 * @param close - Close prices array
 * @param fastperiod - Fast EMA period (default: 12)
 * @param slowperiod - Slow EMA period (default: 26)
 * @param signalperiod - Signal line period (default: 9)
 * @returns Object containing macd, signal, and hist arrays
 */
export declare function macd(close: Array<number>, fastperiod: number, slowperiod: number, signalperiod: number): MacdResult
/**
 * MACD with custom moving average type (async for large datasets)
 *
 * @param close - Close prices array
 * @param fastperiod - Fast period
 * @param slowperiod - Slow period
 * @param signalperiod - Signal period
 * @returns Promise resolving to MacdResult
 */
export declare function macdAsync(close: Array<number>, fastperiod: number, slowperiod: number, signalperiod: number): Promise<MacdResult>
/** Stochastic Oscillator Result */
export interface StochResult {
  k: Array<number>
  d: Array<number>
}
/**
 * Stochastic Oscillator (STOCH)
 *
 * Compares a security's closing price to its price range over a given period.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param fastk_period - %K period (default: 5)
 * @param slowk_period - %K slowing period (default: 3)
 * @param slowd_period - %D period (default: 3)
 * @returns Object containing k and d arrays
 */
export declare function stoch(high: Array<number>, low: Array<number>, close: Array<number>, fastkPeriod: number, slowkPeriod: number, slowdPeriod: number): StochResult
/**
 * Average Directional Index (ADX)
 *
 * Measures trend strength regardless of trend direction.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param timeperiod - Number of periods (default: 14)
 * @returns Array of ADX values
 */
export declare function adx(high: Array<number>, low: Array<number>, close: Array<number>, timeperiod: number): Array<number>
/**
 * Average True Range (ATR)
 *
 * Measures market volatility.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param timeperiod - Number of periods (default: 14)
 * @returns Array of ATR values
 */
export declare function atr(high: Array<number>, low: Array<number>, close: Array<number>, timeperiod: number): Array<number>
/**
 * On Balance Volume (OBV)
 *
 * Measures buying and selling pressure using volume.
 *
 * @param close - Close prices array
 * @param volume - Volume array
 * @returns Array of OBV values
 */
export declare function obv(close: Array<number>, volume: Array<number>): Array<number>
/**
 * Parabolic SAR (SAR)
 *
 * A trend-following indicator that provides stop levels.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param acceleration - Acceleration factor (default: 0.02)
 * @param maximum - Maximum acceleration (default: 0.2)
 * @returns Array of SAR values
 */
export declare function sar(high: Array<number>, low: Array<number>, acceleration: number, maximum: number): Array<number>
/** Aroon Indicator Result */
export interface AroonResult {
  aroonUp: Array<number>
  aroonDown: Array<number>
}
/**
 * Aroon Indicator (AROON)
 *
 * Identifies trend changes and the strength of the trend.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param timeperiod - Number of periods (default: 14)
 * @returns Object containing aroon_up and aroon_down arrays
 */
export declare function aroon(high: Array<number>, low: Array<number>, timeperiod: number): AroonResult
/**
 * Commodity Channel Index (CCI)
 *
 * Measures the current price level relative to an average price level.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param timeperiod - Number of periods (default: 14)
 * @returns Array of CCI values
 */
export declare function cci(high: Array<number>, low: Array<number>, close: Array<number>, timeperiod: number): Array<number>
/**
 * Momentum (MOM)
 *
 * Measures the change in price over a given period.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods
 * @returns Array of momentum values
 */
export declare function mom(close: Array<number>, timeperiod: number): Array<number>
/**
 * Rate of Change (ROC)
 *
 * Measures the percentage change in price over a given period.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods
 * @returns Array of ROC values (percentage)
 */
export declare function roc(close: Array<number>, timeperiod: number): Array<number>
/**
 * Williams %R (WILLR)
 *
 * A momentum indicator that measures overbought/oversold levels.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param timeperiod - Number of periods (default: 14)
 * @returns Array of Williams %R values (-100 to 0)
 */
export declare function willr(high: Array<number>, low: Array<number>, close: Array<number>, timeperiod: number): Array<number>
/**
 * Absolute Price Oscillator (APO)
 *
 * The difference between two moving averages.
 *
 * @param close - Close prices array
 * @param fastperiod - Fast period
 * @param slowperiod - Slow period
 * @returns Array of APO values
 */
export declare function apo(close: Array<number>, fastperiod: number, slowperiod: number): Array<number>
/**
 * Balance of Power (BOP)
 *
 * Measures the strength of buyers vs sellers in the market.
 *
 * @param open - Open prices array
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @returns Array of BOP values
 */
export declare function bop(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Chande Momentum Oscillator (CMO)
 *
 * A momentum indicator that measures the percentage of sum of up days vs sum of down days.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods
 * @returns Array of CMO values (-100 to 100)
 */
export declare function cmo(close: Array<number>, timeperiod: number): Array<number>
/**
 * Directional Movement Index (DX)
 *
 * Measures trend direction and strength.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param timeperiod - Number of periods
 * @returns Array of DX values
 */
export declare function dx(high: Array<number>, low: Array<number>, close: Array<number>, timeperiod: number): Array<number>
/**
 * Money Flow Index (MFI)
 *
 * A momentum indicator that uses both price and volume.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param volume - Volume array
 * @param timeperiod - Number of periods (default: 14)
 * @returns Array of MFI values (0-100)
 */
export declare function mfi(high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>, timeperiod: number): Array<number>
/**
 * Minus Directional Indicator (MINUS_DI)
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param timeperiod - Number of periods
 * @returns Array of MINUS_DI values
 */
export declare function minusDi(high: Array<number>, low: Array<number>, close: Array<number>, timeperiod: number): Array<number>
/**
 * Plus Directional Indicator (PLUS_DI)
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param timeperiod - Number of periods
 * @returns Array of PLUS_DI values
 */
export declare function plusDi(high: Array<number>, low: Array<number>, close: Array<number>, timeperiod: number): Array<number>
/**
 * Triple Exponential Average (TRIX)
 *
 * A momentum oscillator that calculates a triple smoothed EMA.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods
 * @returns Array of TRIX values (percentage)
 */
export declare function trix(close: Array<number>, timeperiod: number): Array<number>
/**
 * Accumulation/Distribution Line (AD)
 *
 * A cumulative indicator that uses volume and price to assess accumulation/distribution.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param volume - Volume array
 * @returns Array of AD values
 */
export declare function ad(high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>): Array<number>
/**
 * Accumulation/Distribution Oscillator (ADOSC)
 *
 * The difference between fast and slow EMA of the A/D line.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param volume - Volume array
 * @param fastperiod - Fast EMA period (default: 3)
 * @param slowperiod - Slow EMA period (default: 10)
 * @returns Array of ADOSC values
 */
export declare function adosc(high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>, fastperiod: number, slowperiod: number): Array<number>
/** Bollinger Bands Result */
export interface BbandsResult {
  upper: Array<number>
  middle: Array<number>
  lower: Array<number>
}
/**
 * Bollinger Bands (BBANDS)
 *
 * Volatility bands placed above and below a moving average.
 *
 * @param close - Close prices array
 * @param timeperiod - Number of periods (default: 5)
 * @param nbdevup - Upper band standard deviations (default: 2.0)
 * @param nbdevdn - Lower band standard deviations (default: 2.0)
 * @returns Object containing upper, middle, and lower arrays
 */
export declare function bollingerBands(close: Array<number>, timeperiod: number, nbdevup: number, nbdevdn: number): BbandsResult
/**
 * Natural Average True Range (NATR)
 *
 * Normalized ATR as a percentage.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param timeperiod - Number of periods (default: 14)
 * @returns Array of NATR values (percentage)
 */
export declare function natr(high: Array<number>, low: Array<number>, close: Array<number>, timeperiod: number): Array<number>
/**
 * True Range (TRANGE)
 *
 * The greatest of the following: high - low, |high - prev_close|, |low - prev_close|.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @returns Array of True Range values
 */
export declare function trange(high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Hilbert Transform - Dominant Cycle Period (HT_DCPERIOD)
 *
 * Measures the dominant cycle period of the price series.
 *
 * @param close - Close prices array
 * @returns Array of dominant cycle period values
 */
export declare function htDcperiod(close: Array<number>): Array<number>
/**
 * Hilbert Transform - Dominant Cycle Phase (HT_DCPHASE)
 *
 * Measures the dominant cycle phase in degrees (0-360).
 *
 * @param close - Close prices array
 * @returns Array of dominant cycle phase values in degrees
 */
export declare function htDcphase(close: Array<number>): Array<number>
/** Hilbert Transform - Phasor Components Result */
export interface HtPhasorResult {
  inPhase: Array<number>
  quadrature: Array<number>
}
/**
 * Hilbert Transform - Phasor Components (HT_PHASOR)
 *
 * Returns the in-phase and quadrature components of the Hilbert Transform.
 *
 * @param close - Close prices array
 * @returns Object containing in_phase and quadrature arrays
 */
export declare function htPhasor(close: Array<number>): HtPhasorResult
/** Hilbert Transform - Sine Wave Result */
export interface HtSineResult {
  sine: Array<number>
  leadSine: Array<number>
}
/**
 * Hilbert Transform - Sine Wave (HT_SINE)
 *
 * Returns the sine wave and lead sine wave components.
 *
 * @param close - Close prices array
 * @returns Object containing sine and lead_sine arrays
 */
export declare function htSine(close: Array<number>): HtSineResult
/**
 * Hilbert Transform - Trend vs Cycle Mode (HT_TRENDMODE)
 *
 * Indicates whether the market is in trend mode (1) or cycle mode (0).
 *
 * @param close - Close prices array
 * @returns Array of mode values (1.0 for trend, 0.0 for cycle)
 */
export declare function htTrendmode(close: Array<number>): Array<number>
/**
 * Hilbert Transform - Instantaneous Trendline (HT_TRENDLINE)
 *
 * Computes the instantaneous trendline with cycle components removed.
 *
 * @param close - Close prices array (typically typical price)
 * @returns Array of trendline values
 */
export declare function htTrendline(close: Array<number>): Array<number>
/**
 * Average Price (AVGPRICE)
 *
 * (open + high + low + close) / 4
 *
 * @param open - Open prices array
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @returns Array of average prices
 */
export declare function avgprice(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Median Price (MEDPRICE)
 *
 * (high + low) / 2
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @returns Array of median prices
 */
export declare function medprice(high: Array<number>, low: Array<number>): Array<number>
/**
 * Typical Price (TYPPRICE)
 *
 * (high + low + close) / 3
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @returns Array of typical prices
 */
export declare function typprice(high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Weighted Close Price (WCLPRICE)
 *
 * (high + low + 2 * close) / 4
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @returns Array of weighted close prices
 */
export declare function wclprice(high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Z-Score (ZSCORE)
 *
 * Calculates the number of standard deviations a data point is from the rolling mean.
 *
 * @param input - Input data array
 * @param timeperiod - Rolling window size
 * @returns Array of Z-Score values
 */
export declare function zscore(input: Array<number>, timeperiod: number): Array<number>
/**
 * Percent Rank (PERCENT_RANK)
 *
 * Calculates the percentage rank of current value within the rolling window.
 *
 * @param input - Input data array
 * @param timeperiod - Rolling window size
 * @returns Array of percent rank values (0-100)
 */
export declare function percentRank(input: Array<number>, timeperiod: number): Array<number>
/**
 * Beta Coefficient (BETA)
 *
 * Measures the volatility of an asset relative to a benchmark.
 *
 * @param asset - Asset price array (e.g., stock)
 * @param benchmark - Benchmark price array (e.g., market index)
 * @param timeperiod - Rolling window size
 * @returns Array of Beta values
 */
export declare function beta(asset: Array<number>, benchmark: Array<number>, timeperiod: number): Array<number>
/**
 * Pearson Correlation (CORREL)
 *
 * Calculates the rolling Pearson correlation coefficient between two series.
 *
 * @param input_a - First data array
 * @param input_b - Second data array
 * @param timeperiod - Rolling window size
 * @returns Array of correlation values (-1 to 1)
 */
export declare function correlation(inputA: Array<number>, inputB: Array<number>, timeperiod: number): Array<number>
/**
 * Standard Deviation (STDDEV)
 *
 * Calculates the rolling sample standard deviation.
 *
 * @param input - Input data array
 * @param timeperiod - Rolling window size
 * @param nb_dev - Number of deviations (for API compatibility)
 * @returns Array of standard deviation values
 */
export declare function stdDev(input: Array<number>, timeperiod: number, nbDev: number): Array<number>
/**
 * Linear Regression (LINEAR_REG)
 *
 * Calculates rolling linear regression predicted values.
 *
 * @param input - Input data array
 * @param timeperiod - Rolling window size
 * @returns Array of linear regression values
 */
export declare function linearReg(input: Array<number>, timeperiod: number): Array<number>
/**
 * Time Series Forecast (TSF)
 *
 * Predicts the next value using linear regression extrapolation.
 *
 * @param input - Input data array
 * @param timeperiod - Rolling window size
 * @returns Array of TSF values
 */
export declare function tsf(input: Array<number>, timeperiod: number): Array<number>
/**
 * Doji Pattern (CDLDOJI)
 *
 * Open and close are virtually the same.
 *
 * @param open - Open prices array
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param doji_pct - Doji threshold percentage (default: 0.1)
 * @returns Array with 100 where pattern detected, 0 otherwise
 */
export declare function cdlDoji(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, dojiPct: number): Array<number>
/**
 * Dragonfly Doji (CDLDRAGONFLYDOJI)
 *
 * Doji with long lower shadow and little to no upper shadow.
 */
export declare function cdlDragonflyDoji(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, dojiPct: number): Array<number>
/**
 * Gravestone Doji (CDLGRAVESTONEDOJI)
 *
 * Doji with long upper shadow and little to no lower shadow.
 */
export declare function cdlGravestoneDoji(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, dojiPct: number): Array<number>
/**
 * Long-Legged Doji (CDLLONGLEGGEDDOJI)
 *
 * Doji with long upper and lower shadows.
 */
export declare function cdlLongLeggedDoji(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, dojiPct: number): Array<number>
/**
 * Hammer (CDLHAMMER)
 *
 * Small body at the top, long lower shadow. Bullish reversal pattern.
 */
export declare function cdlHammer(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Inverted Hammer (CDLINVERTEDHAMMER)
 *
 * Small body at the bottom, long upper shadow. Bullish reversal pattern.
 */
export declare function cdlInvertedHammer(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Hanging Man (CDLHANGINGMAN)
 *
 * Same shape as Hammer but appears after uptrend. Bearish reversal.
 */
export declare function cdlHangingMan(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Shooting Star (CDLSHOOTINGSTAR)
 *
 * Same shape as Inverted Hammer but appears after uptrend. Bearish reversal.
 */
export declare function cdlShootingStar(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Engulfing Pattern (CDLENGULFING)
 *
 * Two-candle pattern where second candle engulfs the first.
 * Returns 100 for bullish, -100 for bearish.
 */
export declare function cdlEngulfing(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Harami Pattern (CDLHARAMI)
 *
 * Two-candle pattern where second candle is contained within the first.
 * Returns 100 for bullish, -100 for bearish.
 */
export declare function cdlHarami(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Harami Cross (CDLHARAMICROSS)
 *
 * Harami where second candle is a Doji.
 * Returns 100 for bullish, -100 for bearish.
 */
export declare function cdlHaramiCross(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Morning Star (CDLMORNINGSTAR)
 *
 * Three-candle bullish reversal pattern.
 */
export declare function cdlMorningStar(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Evening Star (CDLEVENINGSTAR)
 *
 * Three-candle bearish reversal pattern.
 */
export declare function cdlEveningStar(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Morning Doji Star (CDLMORNINGDOJISTAR)
 *
 * Like Morning Star but second candle is a Doji.
 */
export declare function cdlMorningDojiStar(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, dojiPct: number): Array<number>
/**
 * Evening Doji Star (CDLEVENINGDOJISTAR)
 *
 * Like Evening Star but second candle is a Doji.
 */
export declare function cdlEveningDojiStar(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, dojiPct: number): Array<number>
/**
 * Three White Soldiers (CDLTHREEWHITESOLDIERS)
 *
 * Three consecutive bullish candles with higher closes.
 */
export declare function cdlThreeWhiteSoldiers(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Three Black Crows (CDLTHREEBLACKCROWS)
 *
 * Three consecutive bearish candles with lower closes.
 */
export declare function cdlThreeBlackCrows(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Marubozu (CDLMARUBOZU)
 *
 * A candle with no shadows. Returns 100 for bullish, -100 for bearish.
 */
export declare function cdlMarubozu(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, shadowPct: number): Array<number>
/**
 * Piercing Pattern (CDLPIERCING)
 *
 * Two-candle bullish reversal pattern.
 */
export declare function cdlPiercing(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Dark Cloud Cover (CDLDARKCLOUDCOVER)
 *
 * Two-candle bearish reversal pattern.
 */
export declare function cdlDarkCloudCover(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Belt Hold (CDLBELTHOLD)
 *
 * Opens at its high (bearish) or low (bullish) with no shadow.
 */
export declare function cdlBeltHold(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Spinning Top (CDLSPINNINGTOP)
 *
 * Small body with upper and lower shadows of similar length.
 */
export declare function cdlSpinningTop(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * High Wave (CDLHIGHWAVE)
 *
 * Similar to Spinning Top but with longer shadows.
 */
export declare function cdlHighWave(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Rickshaw Man (CDLRICKSHAWMAN)
 *
 * A Doji with long upper and lower shadows near midpoint.
 */
export declare function cdlRickshawMan(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Tweezer Top (CDLTWEEZERTOP)
 *
 * Two candles with matching highs after uptrend.
 */
export declare function cdlTweezerTop(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Tweezer Bottom (CDLTWEEZERBOT)
 *
 * Two candles with matching lows after downtrend.
 */
export declare function cdlTweezerBot(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/**
 * Kicking (CDLKICKING)
 *
 * Two candles with gaps and opposite colors.
 */
export declare function cdlKicking(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>): Array<number>
/** Head and Shoulders Pattern */
export interface HeadShouldersPattern {
  left: number
  head: number
  right: number
}
/**
 * Detect Head and Shoulders Top Pattern
 *
 * @param high - High prices array
 * @param min_bars - Minimum bars between peaks
 * @param head_ratio - Head to shoulder ratio threshold (default: 1.1)
 * @returns Array of detected patterns with left, head, right indices
 */
export declare function detectHeadShoulders(high: Array<number>, minBars: number, headRatio: number): Array<number>
/**
 * Detect Double Top Pattern
 *
 * @param high - High prices array
 * @param lookback - Lookback period for peak detection
 * @param tolerance - Price tolerance for matching peaks (percentage)
 * @returns Array of indices where double tops are detected
 */
export declare function detectDoubleTop(high: Array<number>, lookback: number, tolerance: number): Array<number>
/**
 * Detect Double Bottom Pattern
 *
 * @param low - Low prices array
 * @param lookback - Lookback period for trough detection
 * @param tolerance - Price tolerance for matching troughs (percentage)
 * @returns Array of indices where double bottoms are detected
 */
export declare function detectDoubleBottom(low: Array<number>, lookback: number, tolerance: number): Array<number>
/**
 * Detect Head and Shoulders Bottom (Inverse) Pattern
 *
 * @param low - Low prices array
 * @param min_bars - Minimum bars between troughs
 * @param head_ratio - Head to shoulder ratio threshold
 * @returns Array of detected inverse H&S patterns
 */
export declare function detectHeadShouldersBottom(low: Array<number>, minBars: number, headRatio: number): Array<number>
/**
 * Detect Triple Top Pattern
 *
 * @param high - High prices array
 * @param lookback - Lookback period
 * @param tolerance - Price tolerance (percentage)
 * @returns Array of indices where triple tops are detected
 */
export declare function detectTripleTop(high: Array<number>, lookback: number, tolerance: number): Array<number>
/**
 * Detect Triple Bottom Pattern
 *
 * @param low - Low prices array
 * @param lookback - Lookback period
 * @param tolerance - Price tolerance (percentage)
 * @returns Array of indices where triple bottoms are detected
 */
export declare function detectTripleBottom(low: Array<number>, lookback: number, tolerance: number): Array<number>
/**
 * Ichimoku Cloud Result
 *
 * Contains all five lines of the Ichimoku Kinko Hyo indicator.
 */
export interface IchimokuResult {
  /** Tenkan-sen (Conversion Line) = (9-period high + 9-period low) / 2 */
  tenkanSen: Array<number>
  /** Kijun-sen (Base Line) = (26-period high + 26-period low) / 2 */
  kijunSen: Array<number>
  /** Senkou Span A (Leading Span A) = (Tenkan-sen + Kijun-sen) / 2, shifted forward */
  senkouSpanA: Array<number>
  /** Senkou Span B (Leading Span B) = (52-period high + 52-period low) / 2, shifted forward */
  senkouSpanB: Array<number>
  /** Chikou Span (Lagging Span) = Close price, shifted backward */
  chikouSpan: Array<number>
}
/**
 * Ichimoku Cloud (Ichimoku Kinko Hyo)
 *
 * A comprehensive indicator that shows support and resistance, identifies trend direction,
 * gauges momentum, and provides trading signals.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param tenkan_period - Tenkan-sen period (default: 9)
 * @param kijun_period - Kijun-sen period (default: 26)
 * @param senkou_b_period - Senkou Span B period (default: 52)
 * @returns Object containing tenkanSen, kijunSen, senkouSpanA, senkouSpanB, chikouSpan arrays
 */
export declare function ichimoku(high: Array<number>, low: Array<number>, close: Array<number>, tenkanPeriod: number, kijunPeriod: number, senkouBPeriod: number): IchimokuResult
/**
 * SuperTrend Trend Following Result
 *
 * Contains trend direction, trend line, and upper/lower bands.
 */
export interface SuperTrendResult {
  /** Trend direction: 1 for bullish (up), -1 for bearish (down) */
  direction: Array<number>
  /** SuperTrend trend line (current support/resistance line) */
  trendLine: Array<number>
  /** Upper band */
  upperBand: Array<number>
  /** Lower band */
  lowerBand: Array<number>
}
/**
 * SuperTrend Trend Following Indicator
 *
 * A volatility-based trend following indicator that calculates bands based on ATR.
 * Returns the trend direction, trend line, and upper/lower bands.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param period - ATR calculation period (default: 10)
 * @param multiplier - ATR multiplier (default: 3.0)
 * @returns Object containing direction, trendLine, upperBand, lowerBand arrays
 */
export declare function supertrend(high: Array<number>, low: Array<number>, close: Array<number>, period: number, multiplier: number): SuperTrendResult
/**
 * Volume Weighted Average Price (VWAP)
 *
 * A trading benchmark that represents the average price a security has traded at
 * throughout the day, based on both volume and price.
 *
 * Formula: VWAP = Σ(Typical Price × Volume) / Σ(Volume)
 * where Typical Price = (High + Low + Close) / 3
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param volume - Volume array
 * @returns Array of VWAP values
 */
export declare function vwap(high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>): Array<number>
/**
 * Anchored Volume Weighted Average Price (Anchored VWAP)
 *
 * Similar to VWAP, but allows traders to specify a starting point (anchor) from which
 * the calculation begins. Useful for measuring average price from significant events.
 *
 * Formula: Anchored VWAP = Σ(Typical Price × Volume) / Σ(Volume)
 * where the summation starts from start_index
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param volume - Volume array
 * @param start_index - The index from which to start calculating VWAP
 * @returns Array of Anchored VWAP values (NaN for indices before start_index)
 */
export declare function anchoredVwap(high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>, startIndex: number): Array<number>
/**
 * VWAP Bands Result
 *
 * Contains VWAP line with upper and lower bands based on standard deviation.
 */
export interface VwapBandsResult {
  /** VWAP line (center band) */
  vwap: Array<number>
  /** Upper band (VWAP + nb_dev × std_dev) */
  upper: Array<number>
  /** Lower band (VWAP - nb_dev × std_dev) */
  lower: Array<number>
}
/**
 * Volume Weighted Average Price Bands (VWAP Bands)
 *
 * VWAP Bands consist of the VWAP line with upper and lower bands based on standard
 * deviation. These bands help identify overbought and oversold levels relative to
 * the volume-weighted average price.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param volume - Volume array
 * @param timeperiod - Lookback period for standard deviation calculation
 * @param nb_dev - Number of standard deviations for the bands (default: 2.0)
 * @returns Object containing vwap, upper, and lower arrays
 */
export declare function vwapBands(high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>, timeperiod: number, nbDev: number): VwapBandsResult
/**
 * Elder-Ray Indicator Result
 *
 * Contains Force Index, Bull Power, and Bear Power.
 */
export interface ElderRayResult {
  /** Force Index: (Close - Close[1]) × Volume */
  forceIndex: Array<number>
  /** Bull Power: High - EMA(Close, period) */
  bullPower: Array<number>
  /** Bear Power: Low - EMA(Close, period) */
  bearPower: Array<number>
}
/**
 * Elder-Ray Indicator (ELDER-RAY)
 *
 * Developed by Alexander Elder, this indicator uses three components to evaluate
 * the balance of power between bulls and bears in the market.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param volume - Volume array
 * @param period - EMA lookback period for Bull/Bear Power calculation
 * @returns Object containing forceIndex, bullPower, bearPower arrays
 */
export declare function elderRay(high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>, period: number): ElderRayResult
/**
 * Donchian Channel Result
 *
 * Contains upper, lower, middle bands and width.
 */
export interface DonchianResult {
  /** Upper Band - N-period highest high */
  upper: Array<number>
  /** Lower Band - N-period lowest low */
  lower: Array<number>
  /** Middle Band - (Upper + Lower) / 2 */
  middle: Array<number>
  /** Width - Upper - Lower */
  width: Array<number>
}
/**
 * Donchian Channel (DONCHIAN)
 *
 * A trend-following indicator that displays the highest and lowest prices over a given period.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param period - Lookback period
 * @returns Object containing upper, lower, middle, width arrays
 */
export declare function donchian(high: Array<number>, low: Array<number>, period: number): DonchianResult
/** Pivot Points calculation method enum for Node.js */
export const enum PivotMethod {
  /** Standard (Floor) Pivots - Traditional floor trader pivots */
  Standard = 0,
  /** Fibonacci Pivots - Uses Fibonacci ratios */
  Fibonacci = 1,
  /** Woodie's Pivots - Gives more weight to the close */
  Woodie = 2,
  /** Camarilla Pivots - Tighter ranges using specific ratios */
  Camarilla = 3,
  /** DeMark Pivots - Simplified calculation based on open/close relationship */
  DeMark = 4
}
/**
 * Pivot Points Result
 *
 * Contains pivot point and support/resistance levels.
 */
export interface PivotResult {
  /** Pivot Point */
  pivot: Array<number>
  /** Resistance Level 1 */
  r1: Array<number>
  /** Resistance Level 2 */
  r2: Array<number>
  /** Resistance Level 3 */
  r3: Array<number>
  /** Support Level 1 */
  s1: Array<number>
  /** Support Level 2 */
  s2: Array<number>
  /** Support Level 3 */
  s3: Array<number>
}
/**
 * Pivot Points (PIVOT)
 *
 * Calculates pivot points and support/resistance levels based on previous period's
 * high, low, and close prices.
 *
 * @param high - High prices array (previous period highs)
 * @param low - Low prices array (previous period lows)
 * @param close - Close prices array (previous period closes)
 * @param method - Calculation method (0=Standard, 1=Fibonacci, 2=Woodie, 3=Camarilla, 4=DeMark)
 * @returns Object containing pivot, r1, r2, r3, s1, s2, s3 arrays
 */
export declare function pivotPoints(high: Array<number>, low: Array<number>, close: Array<number>, method: PivotMethod): PivotResult
/**
 * Volume Profile Result
 *
 * Contains Point of Control (POC), Value Area High (VAH), and Value Area Low (VAL).
 */
export interface VolumeProfileResult {
  /** Point of Control - price level with the highest traded volume */
  poc: number
  /** Value Area High - upper boundary of the 70% value area */
  vah: number
  /** Value Area Low - lower boundary of the 70% value area */
  val: number
}
/**
 * Volume Profile
 *
 * Divides the price range into bins and calculates the volume traded at each price level.
 * Used to identify key price levels where significant trading activity occurred.
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param close - Close prices array
 * @param volume - Volume array
 * @param num_bins - Number of price bins for the profile
 * @returns Object containing poc, vah, val
 */
export declare function volumeProfile(high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>, numBins: number): VolumeProfileResult
/**
 * Fibonacci Retracement Level
 *
 * Contains the Fibonacci ratio and corresponding price level.
 */
export interface FibLevel {
  /** Fibonacci ratio (e.g., 0.0, 0.236, 0.382, 0.5, 0.618, 0.786, 1.0, 1.272, 1.618) */
  ratio: number
  /** Price level at the Fibonacci ratio */
  price: number
}
/**
 * Fibonacci Retracement Result
 *
 * Contains all Fibonacci retracement and extension levels.
 */
export interface FibonacciResult {
  /** Array of Fibonacci levels with ratio and price */
  levels: Array<FibLevel>
  /** Trend direction: 1 for uptrend (low before high), -1 for downtrend */
  trend: number
  /** Highest price in the range */
  highPrice: number
  /** Lowest price in the range */
  lowPrice: number
  /** Index of the highest price */
  highIndex: number
  /** Index of the lowest price */
  lowIndex: number
}
/**
 * Fibonacci Retracement
 *
 * Automatically detects the highest and lowest prices in the specified range,
 * determines trend direction, and calculates all standard Fibonacci retracement
 * and extension levels.
 *
 * # Trend Detection
 * - **Uptrend** (trend = 1): Low point occurs before high point
 *   - Retracement calculated from low to high
 *   - Extensions above the high
 *
 * - **Downtrend** (trend = -1): High point occurs before low point
 *   - Retracement calculated from high to low
 *   - Extensions below the low
 *
 * # Fibonacci Levels
 * - Retracement: 0.0, 0.236, 0.382, 0.5, 0.618, 0.786, 1.0
 * - Extension: 1.272, 1.618
 *
 * @param high - High prices array
 * @param low - Low prices array
 * @param start_index - Start index of the range (inclusive)
 * @param end_index - End index of the range (inclusive)
 * @returns Object containing levels, trend, highPrice, lowPrice, highIndex, lowIndex
 */
export declare function fibonacciRetracement(high: Array<number>, low: Array<number>, startIndex: number, endIndex: number): FibonacciResult
export interface KlineDataNapi {
  dates: Array<string>
  opens: Array<number>
  highs: Array<number>
  lows: Array<number>
  closes: Array<number>
  volumes: Array<number>
}
export declare function klineDataNew(dates: Array<string>, opens: Array<number>, highs: Array<number>, lows: Array<number>, closes: Array<number>, volumes: Array<number>): KlineDataNapi
export declare function klineDataValidate(data: KlineDataNapi): boolean
export declare function vortex(high: Array<number>, low: Array<number>, close: Array<number>, timeperiod?: number | undefined | null): Array<Array<number>>
export declare function inertiaIndicator(open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, rviPeriod?: number | undefined | null, linregPeriod?: number | undefined | null): Array<number>
export declare function vzo(close: Array<number>, volume: Array<number>, timeperiod?: number | undefined | null): Array<number>
export declare function volumeMomentum(volume: Array<number>, timeperiod?: number | undefined | null): Array<number>
export declare function volumeRoc(volume: Array<number>, timeperiod?: number | undefined | null): Array<number>
export declare function chandeForecastOscillator(close: Array<number>, timeperiod?: number | undefined | null): Array<number>
export declare function twiggsMoneyFlow(high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>, timeperiod?: number | undefined | null): Array<number>
/**
 * Execute a trading formula
 *
 * This function compiles and executes a trading formula string similar to
 * TongDaXin (通达信) formula language.
 *
 * @param source - Formula source code
 * @param open - Opening prices
 * @param high - High prices
 * @param low - Low prices
 * @param close - Closing prices
 * @param volume - Trading volume
 * @returns Object with output variable names as keys and arrays as values.
 *          The special key "__result__" contains the final expression result.
 *
 * @example
 * ```javascript
 * const result = formulaEval(
 *     "MA5:=MA(C,5); MA10:=MA(C,10); CROSS(MA5, MA10)",
 *     open, high, low, close, volume
 * );
 * console.log(result.MA5);
 * console.log(result.MA10);
 * console.log(result.__result__);
 * ```
 */
export declare function formulaEval(source: string, open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>): Record<string, Array<number>>
export interface FormulaMultiResult {
  names: Array<string>
  values: Array<Array<number>>
  result: Array<number>
}
export declare function formulaEvalMulti(source: string, open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>): FormulaMultiResult
export declare function formulaEvalDraw(source: string, open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>): string
export declare function formulaEvalDebug(source: string, open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>): string
export interface FormulaTemplateInfo {
  name: string
  description: string
  category: string
  source: string
}
export declare function formulaGetTemplate(name: string): FormulaTemplateInfo | null
export declare function formulaSearchTemplates(keyword: string): Array<FormulaTemplateInfo>
export declare function formulaListCategories(): Array<string>
/**
 * Validate a formula without executing
 *
 * Checks if the formula syntax is valid without actually running it.
 *
 * @param source - Formula source code to validate
 * @returns `true` if the formula is syntactically valid, `false` otherwise.
 */
export declare function formulaValidate(source: string): boolean
/**
 * Execute a trading formula with JIT compilation
 *
 * Compiles the formula using Just-In-Time compilation for maximum execution speed.
 * This is ideal for formulas that need to be executed repeatedly with different data.
 *
 * @param source - Formula source code
 * @param open - Opening prices
 * @param high - High prices
 * @param low - Low prices
 * @param close - Closing prices
 * @param volume - Trading volume
 * @returns Object with output variable names as keys and arrays as values.
 *          The special key "__result__" contains the final expression result.
 */
export declare function formulaEvalJit(source: string, open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>): Record<string, Array<number>>
/**
 * Execute a trading formula with SIMD optimization
 *
 * Uses SIMD (Single Instruction Multiple Data) vectorization to accelerate
 * formula execution on supported hardware. Best suited for data-parallel
 * operations on large datasets.
 *
 * @param source - Formula source code
 * @param open - Opening prices
 * @param high - High prices
 * @param low - Low prices
 * @param close - Closing prices
 * @param volume - Trading volume
 * @returns Object with output variable names as keys and arrays as values.
 *          The special key "__result__" contains the final expression result.
 */
export declare function formulaEvalSimd(source: string, open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>): Record<string, Array<number>>
/**
 * Execute a trading formula with SIMD optimization
 *
 * Minimizes memory allocations by operating directly on input buffers
 * without copying data. This provides the lowest latency execution path
 * for latency-sensitive applications.
 *
 * @param source - Formula source code
 * @param open - Opening prices
 * @param high - High prices
 * @param low - Low prices
 * @param close - Closing prices
 * @param volume - Trading volume
 * @returns Object with output variable names as keys and arrays as values.
 *          The special key "__result__" contains the final expression result.
 */
export declare function formulaEvalZeroCopy(source: string, open: Array<number>, high: Array<number>, low: Array<number>, close: Array<number>, volume: Array<number>): Record<string, Array<number>>
export declare class NapiStreamingSma {
  constructor(period: number)
  update(value: number): number
  updateBatch(values: Array<number>): Array<number>
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingEma {
  constructor(period: number)
  update(value: number): number
  updateBatch(values: Array<number>): Array<number>
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingWma {
  constructor(period: number)
  update(value: number): number
  updateBatch(values: Array<number>): Array<number>
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingDema {
  constructor(period: number)
  update(value: number): number
  updateBatch(values: Array<number>): Array<number>
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingTema {
  constructor(period: number)
  update(value: number): number
  updateBatch(values: Array<number>): Array<number>
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingKama {
  constructor(period: number)
  update(value: number): number
  updateBatch(values: Array<number>): Array<number>
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingT3 {
  constructor(period: number)
  update(value: number): number
  updateBatch(values: Array<number>): Array<number>
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingRsi {
  constructor(period: number)
  update(value: number): number
  updateBatch(values: Array<number>): Array<number>
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingMom {
  constructor(period: number)
  update(value: number): number
  updateBatch(values: Array<number>): Array<number>
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingRoc {
  constructor(period: number)
  update(value: number): number
  updateBatch(values: Array<number>): Array<number>
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingMacd {
  constructor(fastPeriod?: number | undefined | null, slowPeriod?: number | undefined | null, signalPeriod?: number | undefined | null)
  update(value: number): MacdResult
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingBoll {
  constructor(period?: number | undefined | null, nbDevUp?: number | undefined | null, nbDevDn?: number | undefined | null)
  update(value: number): BollResult
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingAtr {
  constructor(period: number)
  update(high: number, low: number, close: number): number
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingAdx {
  constructor(period: number)
  update(high: number, low: number, close: number): number
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingCci {
  constructor(period: number)
  update(high: number, low: number, close: number): number
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingStoch {
  constructor(kPeriod?: number | undefined | null, kSlow?: number | undefined | null, dPeriod?: number | undefined | null)
  update(high: number, low: number, close: number): StochResult
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingAroon {
  constructor(period?: number | undefined | null)
  update(high: number, low: number): AroonResult
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingObv {
  constructor()
  update(open: number, high: number, low: number, close: number, volume: number): number
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingVwap {
  constructor()
  update(open: number, high: number, low: number, close: number, volume: number): number
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingWillr {
  constructor(period: number)
  update(open: number, high: number, low: number, close: number, volume: number): number
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingMfi {
  constructor(period: number)
  update(open: number, high: number, low: number, close: number, volume: number): number
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingNatr {
  constructor(period: number)
  update(open: number, high: number, low: number, close: number, volume: number): number
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingTrange {
  constructor()
  update(open: number, high: number, low: number, close: number, volume: number): number
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingDonchian {
  constructor(period?: number | undefined | null)
  update(open: number, high: number, low: number, close: number, volume: number): DonchianResult
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingIchimoku {
  constructor(tenkan?: number | undefined | null, kijun?: number | undefined | null, senkouB?: number | undefined | null)
  update(open: number, high: number, low: number, close: number, volume: number): IchimokuResult
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingSupertrend {
  constructor(period?: number | undefined | null, multiplier?: number | undefined | null)
  update(open: number, high: number, low: number, close: number, volume: number): SuperTrendResult
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class NapiStreamingKeltner {
  constructor(emaPeriod?: number | undefined | null, atrPeriod?: number | undefined | null, multiplier?: number | undefined | null)
  update(open: number, high: number, low: number, close: number, volume: number): KeltnerResult
  reset(): void
  get isReady(): boolean
  get count(): number
}
export declare class Pipeline {
  constructor()
  addLogReturn(): this
  addPctChange(): this
  addZscore(): this
  addStandardScaler(): this
  addMinMaxScaler(): this
  addRank(): this
  addPercentileRank(): this
  addDiff(): this
  addDiffN(order: number): this
  addRollingMean(window: number): this
  addRollingStd(window: number): this
  addRollingSum(window: number): this
  transform(data: Array<number>): Array<number>
}
export declare class KlineChartNapi {
  constructor(data: KlineDataNapi, language: string, title: string, width: number, height: number)
  addMa(periods: Array<number>): void
  addMacd(fast: number, slow: number, signal: number): void
  addRsi(period: number): void
  addBoll(period: number, nbDev: number): void
  saveAsSvg(path: string): void
  toSvg(): string
}
